In [79]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [80]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### BUILDING PERMITS

In [81]:
#importing in bulding permit data
building_permits = pd.read_csv('/content/drive/MyDrive/detroit data/building_permits_2023_5461986780762354220.csv')
building_permits.head(1)

,Record ID,Street Number,Street Direction,Street Name,Street Type,Date Submitted,Date Issued,Permit Status,Permit Payment Amount,Building Legal Use,Stories,Zoning Code,Proposed Use,Type of Construction,Permit Type,Description of Work,Contractor Estimated Cost,Department Estimated Cost,Parcel ID,Latitude,Longitude,ObjectId,Address ID,Open to Elements?,Missing Portions?,Purchased From DLBA?,DLBA Compliant?,Change in Units?,Vacant?,x,y
0,BLD2010-03399,14401,NaN,PIERSON,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22107015.,42.392052,-83.246171,1,545664.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.266921e+06,5.219889e+06

In [82]:
#parcel id date and permit are the only columns needed for now
columns_to_keep = ['Parcel ID', 'Date Issued', 'Permit Status']
building_permits_1 = building_permits[columns_to_keep]

building_permits_1.head(1)

   Parcel ID            Date Issued Permit Status
0  22107015.  7/27/2020 12:00:00 AM        Issued

### BLIGHT VIOLATIONS

In [83]:
#importing in blight violation data
blight_violations = pd.read_csv('/content/drive/MyDrive/detroit data/blight_violations (1).csv')
blight_violations.head(1)
#parcelno

<ipython-input-83-db77d960083b>:2: DtypeWarning: Columns (8,10,15,16,17,37) have mixed types. Specify dtype option on import or set low_memory=False.
  blight_violations = pd.read_csv('/content/drive/MyDrive/detroit data/blight_violations (1).csv')

,ticket_id,ticket_number,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_address,violation_zip_code,violator_id,mailing_address_street_number,mailing_address_street_name,mailing_address,city,state,zip_code,non_us_str_code,country,violation_date,ticket_issued_time,hearing_date,hearing_time,judgment_date,ordinance_law,ordinance_description,disposition,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,parcelno,longitude,latitude,address_id,updated_at,ESRI_OID
0,19939,05002662DAH,"Buildings, Safety Engineering & Env Department",Joseph Otis,PRESTIGE CLEANERS,660,WOODWARD AVE,660 WOODWARD AVE,NaN,2523,660,WOODWARD,660 WOODWARD,DETROIT,MI,48226,NaN,NaN,1107216000000,1727173800000,1.111018e+12,10:30AM,1.111450e+12,9-1-36(a),Failure of owner to obtain certificate of comp...,Responsible,250.0,20,10,0.0,0.0,NaN,280.0,0.0,280.0,NaN,NO PAYMENT APPLIED,NaN,01004105.,-83.04554,42.33103,348114.0,1111498938263,1

In [84]:
# parcelno, date, fine amount are the only ones needed
columns_to_keep = ['parcelno', 'violation_date', 'fine_amount']
blight_violations_1 = blight_violations[columns_to_keep]

blight_violations_1.head(1)

    parcelno  violation_date  fine_amount
0  01004105.   1107216000000        250.0

In [85]:
#dropping N/A's
blight_violations_1 = blight_violations_1[blight_violations_1['violation_date'].notna()]
blight_violations_1 = blight_violations_1[blight_violations_1['parcelno'].notna()]
blight_violations_1 = blight_violations_1[blight_violations_1['fine_amount'].notna()]

In [86]:
#filter out all rows where violation_date is not 13-those must have been inputted incorrectly and will not convert to readable date correclty theres only 23 of them
blight_violations_1['violation_date'] = blight_violations_1['violation_date'].astype(str)

blight_violations_1 = blight_violations_1[blight_violations_1['violation_date'].str.isdigit() & (blight_violations_1['violation_date'].str.len() == 13)]

len(blight_violations_1)

727975

In [87]:
#now we have to convert the unix timestamp in the violation_date to a readbable date (using ms) becuase its 13 digits i think
blight_violations_1['violation_date'] = pd.to_datetime(blight_violations_1['violation_date'], unit='ms')

blight_violations_1.head()

<ipython-input-87-c037620e16f7>:2: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  blight_violations_1['violation_date'] = pd.to_datetime(blight_violations_1['violation_date'], unit='ms')

      parcelno violation_date  fine_amount
0    01004105.     2005-02-01        250.0
1    22055135.     2005-01-31        100.0
2    22055131.     2005-01-31        100.0
3  22029963-72     2005-01-28        100.0
4    22054318.     2005-01-31        100.0

In [88]:
#####

In [89]:
# parcels = pd.read_csv('C:/Users/mhviz/mlb-fast-prop/detroit_housing_data.gitignore/Parcels.csv', low_memory = False)
# parcels.head(1)
# #parcel_number

In [90]:
# #changing building_permits parcel id to parcel_number

# building_permits = building_permits.rename(columns={"Parcel ID": "parcel_number"})

In [91]:
# #changing blight_violations parcelno to parcel_number

# blight_violations = blight_violations.rename(columns={"parcelno": "parcel_number"})
# blight_violations.head()

In [92]:
# #merging building_permits and blight_violations
# merged_permits_and_violations = pd.merge(building_permits, blight_violations, on='parcel_number')

# merged_permits_and_violations.len()

### PARCELS

In [93]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np

In [94]:
parcels = pd.read_csv('/content/drive/MyDrive/detroit data/parcel_file_current_3346032144909824368.csv', low_memory = False)
parcels.head(1)

,object_id,Parcel ID,Address,ZIP Code,Taxpayer 1,Taxpayer 2,Taxpayer Address,Taxpayer City,Taxpayer State,Taxpayer ZIP Code,Property Class,Property Class Description,Previous Property Class,Use Code,Use Code Description,Zoning District,Year Built,Building Style,Building Count,Total Floor Area,Tax Status,Tax Status Description,Previous Tax Status,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Principal Residence Exemption % Claimed,NEZ District,ECF Neighborhood,Is Improved,Related Parcel ID,Sale Date,Sale Price,Total Square Footage,Total Acreage,Frontage,Depth,Parcel Modified Date,Legal Description,Ward,Landmap,Subdivision,Local Historic District,Neighborhood,Council District,Street Number,Street Prefix,Street Name,ObjectId,Shape__Area,Shape__Length
0,24265600,21019476.,13702 EASTWOOD,48205,"BOOKER, TRANYSSA",NaN,13667 SARATOGA,DETROIT,MI,48205,402.0,RESIDENTIAL-VACANT,402.0,00003,VACANT RESIDENTIAL,R2,NaN,NaN,0.0,NaN,TAXABLE,TAXABLE,TAXABLE,400.0,400.0,400.0,400.0,0.0,NaN,3R321,0.0,NaN,NaN,0.0,4617.0,0.106,35.0,131.0,NaN,Property exempt from Ad Valorem taxes and asse...,21.0,539,NaN,NaN,Franklin,3.0,13702.0,NaN,EASTWOOD,1,786.476562,137.760108

In [95]:
parcels1 = parcels[["Parcel ID",
                    "Taxpayer City",
                    "Property Class",
                    "Property Class Description",
                    "Tax Status",
                    "Total Square Footage",
                    "Total Acreage",
                    "Frontage",
                    "Depth",
                    "NEZ District",
                    "Building Count",
                    "Year Built",
                    "Sale Price",
                    "Sale Date",
                    "Previous Assessed Value",
                    "Previous Taxable Value",
                    "Neighborhood",
                    "Use Code",
                    "Use Code Description",
                    ]]
parcels2 = parcels1[parcels1["Property Class"].isin([401,402])]
parcels2.head(10)

,Parcel ID,Taxpayer City,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description
0,21019476.,DETROIT,402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL
1,21019749.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN
2,21019245.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN
3,21019205.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN
4,21048771.,DETROIT,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL
5,21042930-1,DETROIT,402.0,RESIDENTIAL-VACANT,TAXABLE,3049.0,0.070,30.0,102.0,NaN,0.0,NaN,0.0,NaN,300.0,300.0,West End,00003,VACANT RESIDENTIAL
6,21042799.,DETROIT,402.0,RESIDENTIAL-VACANT,TAXABLE,3311.0,0.076,32.0,103.0,NaN,0.0,NaN,49500.0,8/21/2007 12:00:00 AM,0.0,0.0,West End,00003,VACANT RESIDENTIAL
7,21047341.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,0.084,30.0,122.0,NaN,0.0,NaN,14000.0,7/1/1971 12:00:00 AM,0.0,0.0,Fox Creek,00VAC,NaN
8,21047551.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4792.0,0.110,40.0,120.0,NaN,0.0,NaN,7300.0,10/1/1981 12:00:00 AM,0.0,0.0,Fox Creek,00VAC,NaN
9,21047578.,DETROIT,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4270.0,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Riverbend,00VAC,NaN

In [96]:
parcels2["Taxpayer City"] = np.where(parcels2["Taxpayer City"] == "DETROIT", 1, 0)

<ipython-input-96-ad77c6b306d4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  parcels2["Taxpayer City"] = np.where(parcels2["Taxpayer City"] == "DETROIT", 1, 0)

In [97]:
parcels2.head(10)

,Parcel ID,Taxpayer City,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description
0,21019476.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL
1,21019749.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN
2,21019245.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN
3,21019205.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN
4,21048771.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL
5,21042930-1,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3049.0,0.070,30.0,102.0,NaN,0.0,NaN,0.0,NaN,300.0,300.0,West End,00003,VACANT RESIDENTIAL
6,21042799.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3311.0,0.076,32.0,103.0,NaN,0.0,NaN,49500.0,8/21/2007 12:00:00 AM,0.0,0.0,West End,00003,VACANT RESIDENTIAL
7,21047341.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,0.084,30.0,122.0,NaN,0.0,NaN,14000.0,7/1/1971 12:00:00 AM,0.0,0.0,Fox Creek,00VAC,NaN
8,21047551.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4792.0,0.110,40.0,120.0,NaN,0.0,NaN,7300.0,10/1/1981 12:00:00 AM,0.0,0.0,Fox Creek,00VAC,NaN
9,21047578.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4270.0,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Riverbend,00VAC,NaN

### POLICE DATA

In [98]:
police =pd.read_csv('/content/drive/MyDrive/detroit data/Police_Serviced_911_Calls_805604165310935371.csv')
police1 = police.loc[:,['Code Description','Category','Priority','Call Time','Neighborhood Name','Council District']]

In [99]:
group1 = ['P', '1','2','3']
def p1(Priority):
  if Priority in group1:
    return 1
  else:
    return 0
police1['High_Priority'] = police1['Priority'].apply(p1)
police1.head()

,Code Description,Category,Priority,Call Time,Neighborhood Name,Council District,High_Priority
0,INVESTIGATE AUTO,INVAUTO,5,8/7/2024 2:01:09 PM,Franklin,3.0,0
1,VERIFIED ALR / PERSON W/O CODE,VERALRM,2,8/7/2024 1:49:28 PM,Historic Atkinson,5.0,1
2,UNKNOWN PROBLEM,UNKPROB,2,8/7/2024 1:49:26 PM,Krainz Woods,3.0,1
3,UNKNOWN PROBLEM,UNKPROB,2,8/7/2024 1:43:08 PM,New Center Commons,5.0,1
4,WELL BEING CHECK,WBC,3,8/7/2024 1:37:50 PM,Central Southwest,6.0,1

In [100]:
police1[['Month','Day', 'temp']] = police1['Call Time'].str.split('/',expand=True)
police1=police1.drop(columns=['Call Time','Month','Day'])
def getYear(y):
 if y:
  return y[0:4]

police1['Year'] = police1['temp'].apply(getYear)
police1.head()

,Code Description,Category,Priority,Neighborhood Name,Council District,High_Priority,temp,Year
0,INVESTIGATE AUTO,INVAUTO,5,Franklin,3.0,0,2024 2:01:09 PM,2024
1,VERIFIED ALR / PERSON W/O CODE,VERALRM,2,Historic Atkinson,5.0,1,2024 1:49:28 PM,2024
2,UNKNOWN PROBLEM,UNKPROB,2,Krainz Woods,3.0,1,2024 1:49:26 PM,2024
3,UNKNOWN PROBLEM,UNKPROB,2,New Center Commons,5.0,1,2024 1:43:08 PM,2024
4,WELL BEING CHECK,WBC,3,Central Southwest,6.0,1,2024 1:37:50 PM,2024

In [101]:
police1 = police1.loc[police1['Year'].isin(['2019', '2020', '2021', '2022', '2023'])]
policd1 = police1.loc[police1['High_Priority'] == 1]
police1 = police1.drop(columns=['temp','Code Description','Category','Priority','Council District'])
police1.head()

        Neighborhood Name  High_Priority  Year
194056     Dexter-Linwood              1  2023
194057            Midwest              1  2023
194058  Central Southwest              1  2023
194059  Bethune Community              1  2023
194060       Elmwood Park              1  2023

In [102]:
count_df = police1.groupby(['Year', 'Neighborhood Name']).size().reset_index(name='count')
finalpolice_df = count_df.groupby('Neighborhood Name')['count'].mean().reset_index(name='yearly_average')
#gives yearly high priority serviced calls by neighborhood
finalpolice_df.head()

  Neighborhood Name  yearly_average
0       Airport Sub          3553.2
1        Arden Park            62.6
2      Aviation Sub           818.6
3            Bagley          3233.4
4  Barton-McFarland          4377.8

### MERGING DATASETS

parcels2

In [103]:
blight = blight_violations_1
policedf = finalpolice_df
#parcels2
bpermits = building_permits_1

In [104]:
blight1 = blight.loc[blight['violation_date'] >= '2019-01-01']

In [105]:
blight1.head()

         parcelno violation_date  fine_amount
374225  22086750.     2019-03-23        200.0
391218  21077857.     2020-10-01        500.0
391220  21077857.     2020-10-01        250.0
394859  21062691.     2020-10-30        250.0
402000  22121565.     2019-01-02        250.0

In [106]:
blight2 = blight1.loc[blight1.groupby('parcelno')['violation_date'].idxmax()]
blight2.head()

             parcelno violation_date  fine_amount
462442      01000001.     2020-01-23        250.0
459231  01000004.002L     2020-01-08        250.0
594863   01000007.001     2022-04-13        250.0
460535      01000087.     2020-01-09        250.0
645649   01000088-109     2023-03-29        250.0

In [107]:
permtemp = bpermits
permtemp['Date Issued'] = pd.to_datetime(permtemp['Date Issued'])
bpermits1 = permtemp
bpermits1.head(2)

<ipython-input-107-a9426a4f9649>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  permtemp['Date Issued'] = pd.to_datetime(permtemp['Date Issued'])
<ipython-input-107-a9426a4f9649>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  permtemp['Date Issued'] = pd.to_datetime(permtemp['Date Issued'])

   Parcel ID Date Issued Permit Status
0  22107015.  2020-07-27        Issued
1  22104480.  2020-07-20        Issued

In [108]:
bpermits2 = bpermits1.loc[bpermits1.groupby('Parcel ID')['Date Issued'].idxmax()]
bpermits2.head()

      Parcel ID Date Issued Permit Status
3748       -501  2019-02-21        Issued
7250       -502  2019-10-24        Issued
29214      -504  2024-05-07        Issued
26507      -506  2024-01-10        Issued
1506       -507  2019-01-31        Issued

In [109]:
blight2.head()

             parcelno violation_date  fine_amount
462442      01000001.     2020-01-23        250.0
459231  01000004.002L     2020-01-08        250.0
594863   01000007.001     2022-04-13        250.0
460535      01000087.     2020-01-09        250.0
645649   01000088-109     2023-03-29        250.0

In [110]:
blight2 = blight2.rename(columns={})

In [111]:
try1 = pd.merge(parcels2, bpermits2, how='left', on='Parcel ID')
try1fix = try1.dropna(subset='Parcel ID')
try1fix.head(5)

,Parcel ID,Taxpayer City,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Date Issued,Permit Status
0,21019476.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,NaT,NaN
1,21019749.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN
2,21019245.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN
3,21019205.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN
4,21048771.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN

In [112]:
try2 = pd.merge(try1fix, blight2, how="left", left_on='Parcel ID', right_on='parcelno')
try2fix = try2.dropna(subset='Parcel ID')
try2fix.head(200)

,Parcel ID,Taxpayer City,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Date Issued,Permit Status,parcelno,violation_date,fine_amount
0,21019476.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
1,21019749.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
2,21019245.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
3,21019205.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
4,21048771.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,21048771.,2019-03-13,250.0
5,21042930-1,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3049.0,0.070,30.0,102.0,NaN,0.0,NaN,0.0,NaN,300.0,300.0,West End,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
6,21042799.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3311.0,0.076,32.0,103.0,NaN,0.0,NaN,49500.0,8/21/2007 12:00:00 AM,0.0,0.0,West End,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
7,21047341.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,0.084,30.0,122.0,NaN,0.0,NaN,14000.0,7/1/1971 12:00:00 AM,0.0,0.0,Fox Creek,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
8,21047551.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4792.0,0.110,40.0,120.0,NaN,0.0,NaN,7300.0,10/1/1981 12:00:00 AM,0.0,0.0,Fox Creek,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
9,21047578.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4270.0,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Riverbend,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
10,21047831.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4283.0,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,800.0,232.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
11,21048345.,0,402.0,RESIDENTIAL-VACANT,EXEMPT (125.1415A),4008.0,0.092,40.0,100.0,NaN,0.0,NaN,2691.0,7/26/2004 12:00:00 AM,0.0,0.0,Jefferson Chalmers,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
12,21048148.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3013.0,0.069,30.0,100.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Jefferson Chalmers,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
13,21050070.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3210.0,0.074,30.0,107.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Riverbend,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
14,21050056.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3180.0,0.073,30.0,106.0,NaN,0.0,NaN,632.0,11/1/1995 12:00:00 AM,0.0,0.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
15,21049906.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3500.0,0.080,35.0,100.0,NaN,0.0,NaN,500.0,10/10/2007 12:00:00 AM,300.0,221.0,Chandler Park,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
16,21033718.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3850.0,0.088,35.0,110.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Von Steuben,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
17,21048812.002L,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,0.084,30.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Riverbend,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
18,21048804.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,0.084,30.0,122.0,NaN,0.0,NaN,13000.0,7/1/1970 12:00:00 AM,0.0,0.0,Riverbend,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
19,21048953.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3615.0,0.083,30.0,121.0,NaN,0.0,NaN,7600.0,5/1/1968 12:00:00 AM,500.0,114.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
20,21076071.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6882.0,0.158,60.0,114.0,NaN,0.0,NaN,7500.0,8/11/2008 12:00:00 AM,0.0,0.0,Cornerstone Village,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
21,21074089.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4428.0,0.102,39.0,114.0,NaN,0.0,NaN,105000.0,8/24/2006 12:00:00 AM,500.0,500.0,Denby,00003,VACANT RESIDENTIAL,NaT,NaN,21074089.,2021-11-02,500.0
22,21080882.,0,402.0,RESIDENTIAL-VACANT,TAXABLE,5619.0,0.129,47.0,120.0,Outer Drive - Gratiot (H057),0.0,NaN,5600.0,10/16/2017 12:00:00 AM,500.0,500.0,Wade,00003,VACANT RESIDENTIAL,NaT,NaN,21080882.,2019-08-13,125.0
23,21080731.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,6011.0,0.138,50.0,120.0,Outer Drive - Gratiot (H057),0.0,NaN,9000.0,8/21/2017 12:00:00 AM,500.0,500.0,Eden Gardens,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
24,21080796.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,5657.0,0.130,47.0,120.0,Outer Drive - Gratiot (H057),0.0,NaN,98421.0,10/24/2003 12:00:00 AM,500.0,500.0,Eden Gardens,00003,VACANT RESIDENTIAL,NaT,NaN,21080796.,2024-06-26,125.0
25,21065437.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3659.0,0.084,30.0,122.0,NaN,0.0,NaN,6300.0,5/23/2003 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
26,21065434.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3668.0,0.084,30.0,122.0,NaN,0.0,NaN,9885.0,10/1/1981 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
27,21064654.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3659.0,0.084,30.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
28,21068129.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5389.0,0.124,45.0,120.0,NaN,0.0,NaN,40900.0,8/1/1996 12:00:00 AM,0.0,0.0,Yorkshire Woods,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
29,21064577.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3441.0,0.079,30.0,115.0,Warren - Alter Rd (H060),0.0,NaN,1000.0,7/4/2002 12:00:00 AM,300.0,300.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
30,21064553.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3441.0,0.079,30.0,115.0,Warren - Alter Rd (H060),0.0,NaN,0.0,NaN,300.0,232.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
31,21064350.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4008.0,0.092,35.0,114.0,NaN,0.0,NaN,44000.0,8/1/1998 12:00:00 AM,0.0,0.0,Morningside,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
32,21064333.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4008.0,0.092,35.0,114.0,NaN,0.0,NaN,9000.0,4/1/1982 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
33,21064409.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3964.0,0.091,35.0,114.0,Warren - Alter Rd (H060),0.0,NaN,2500.0,9/26/2008 12:00:00 AM,400.0,400.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
34,21063089.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7M),3510.0,0.081,30.0,117.0,NaN,0.0,NaN,7300.0,7/13/2007 12:00:00 AM,0.0,0.0,Fox Creek,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
35,21062884.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3511.0,0.081,35.0,101.0,Warren - Alter Rd (H060),0.0,NaN,0.0,NaN,0.0,0.0,Morningside,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
36,21063051.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3131.0,0.072,30.0,104.0,NaN,0.0,NaN,11020.0,3/1/1974 12:00:00 AM,0.0,0.0,Fox Creek,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN
37,21062560.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3453.0,0.079,30.0,115.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Jefferson Chalmers,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
38,21062364.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3000.0,0.069,30.0,100.0,NaN,0.0,NaN,12900.0,12/1/1974 12:00:00 AM,300.0,300.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
39,21062398.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3006.0,0.069,30.0,100.0,NaN,0.0,NaN,11000.0,5/1/1980 12:00:00 AM,300.0,300.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
40,21010242.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4254.0,0.098,40.0,106.0,NaN,0.0,NaN,2350.0,8/1/1988 12:00:00 AM,0.0,0.0,Outer Drive-Hayes,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
41,21014737.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3833.0,0.088,35.0,110.0,NaN,0.0,NaN,11337.0,5/1/1989 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
42,21017765.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4112.0,0.094,40.0,112.0,NaN,0.0,NaN,20500.0,10/1/1981 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
43,21017614.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3615.0,0.083,35.0,103.0,NaN,0.0,NaN,16457.0,3/1/1980 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
44,21017872.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3703.0,0.085,36.0,103.0,NaN,0.0,NaN,4000.0,8/1/1996 12:00:00 AM,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
45,21017893.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4138.0,0.095,40.0,103.0,NaN,0.0,NaN,900.0,2/22/2008 12:00:00 AM,0.0,0.0,Mapleridge,41310,INCOME BUNGALOW,NaT,NaN,NaN,NaT,NaN
46,21018087.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3441.0,0.079,33.0,103.0,NaN,0.0,NaN,9000.0,8/30/2004 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
47,21018086.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3441.0,0.079,33.0,103.0,NaN,0.0,NaN,8000.0,9/1/1993 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
48,21018132.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3703.0,0.085,36.0,103.0,NaN,0.0,NaN,6500.0,12/1/1988 12:00:00 AM,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
49,21013047.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3790.0,0.087,35.0,109.0,NaN,0.0,NaN,14900.0,10/1/1987 12:00:00 AM,0.0,0.0,Gratiot-Findlay,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
50,21013433.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4231.0,0.097,35.0,121.0,NaN,0.0,NaN,6350.0,1/1/1993 12:00:00 AM,0.0,0.0,LaSalle College Park,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
51,21014512.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3441.0,0.079,30.0,114.0,NaN,0.0,NaN,500.0,7/17/2008 12:00:00 AM,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
52,21014673.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3877.0,0.089,35.0,111.0,NaN,0.0,NaN,2000.0,4/1/1987 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
53,21015869.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3833.0,0.088,35.0,110.0,NaN,0.0,NaN,12500.0,11/8/2004 12:00:00 AM,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
54,21014829.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3920.0,0.090,35.0,112.0,NaN,0.0,NaN,22500.0,1/1/1982 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
55,21014948.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4291.0,0.099,38.0,112.0,NaN,0.0,NaN,501.0,9/3/2005 12:00:00 AM,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
56,21014871.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3920.0,0.090,35.0,112.0,NaN,0.0,NaN,1600.0,9/20/2010 12:00:00 AM,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,21014871.,2022-07-09,500.0
57,21015261.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3360.0,0.077,30.0,112.0,NaN,0.0,NaN,14500.0,7/1/1969 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
58,21015228.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3354.0,0.077,30.0,112.0,NaN,0.0,NaN,8500.0,6/1/1985 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
59,21015320.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3354.0,0.077,30.0,112.0,NaN,0.0,NaN,0.0,NaN,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
60,21035950.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5401.0,0.124,40.0,135.0,NaN,0.0,NaN,48814.0,7/5/2011 12:00:00 AM,0.0,0.0,Pulaski,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
61,21035446.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4400.0,0.101,35.0,126.0,NaN,0.0,NaN,26000.0,11/1/1978 12:00:00 AM,400.0,400.0,Pulaski,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
62,21034775.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5097.0,0.117,40.0,127.0,NaN,0.0,NaN,5000.0,6/10/2009 12:00:00 AM,0.0,0.0,Conner Creek,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
63,21034654.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4746.0,0.109,35.0,136.0,NaN,0.0,NaN,95000.0,10/17/2005 12:00:00 AM,400.0,400.0,Von Steuben,00VAC,NaN,NaT,NaN,21034654.,2023-08-24,50.0
64,21033679.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4051.0,0.093,40.0,101.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,LaSalle College Park,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
65,21018640.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6173.0,0.142,60.0,103.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
66,21010270-2,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7M),29648.0,0.681,218.0,136.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Outer Drive-Hayes,00001,IMPROVED NO BLDG,NaT,NaN,NaN,NaT,NaN
67,21010384.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4008.0,0.092,35.0,115.0,NaN,0.0,NaN,3000.0,7/13/2007 12:00:00 AM,0.0,0.0,Outer Drive-Hayes,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
68,21010404.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,0.099,40.0,107.0,NaN,0.0,NaN,29500.0,7/26/2005 12:00:00 AM,0.0,0.0,Outer Drive-Hayes,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN
69,21009020.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7M),4200.0,0.096,40.0,105.0,NaN,0.0,NaN,19500.0,4/1/1979 12:00:00 AM,0.0,0.0,Wade,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
70,21009030.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3659.0,0.084,35.0,105.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Wade,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
71,21009072.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3674.0,0.084,35.0,105.0,NaN,0.0,NaN,21000.0,1/1/1993 12:00:00 AM,200.0,200.0,Wade,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
72,21020355.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4356.0,0.100,38.0,115.0,NaN,0.0,NaN,52324.0,10/11/2007 12:00:00 AM,0.0,0.0,Von Steuben,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
73,21019065.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4138.0,0.095,40.0,103.0,NaN,0.0,NaN,4767.0,5/1/1989 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
74,21018431.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4017.0,0.092,39.0,103.0,NaN,0.0,NaN,11500.0,8/1/1978 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
75,21018455.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3703.0,0.085,36.0,103.0,NaN,0.0,NaN,4000.0,11/1/1978 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
76,21018465.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6874.0,0.158,42.0,164.0,NaN,0.0,NaN,7500.0,2/23/2006 12:00:00 AM,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
77,21019445.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3708.0,0.085,36.0,103.0,NaN,0.0,NaN,2500.0,3/1/1995 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
78,21023505.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5271.0,0.121,42.0,125.0,NaN,0.0,NaN,30000.0,10/1/2012 12:00:00 AM,0.0,0.0,Regent Park,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
79,21022766.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3136.0,0.072,30.0,104.0,NaN,0.0,NaN,35000.0,8/9/2005 12:00:00 AM,200.0,200.0,Regent Park,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
80,21022404.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4138.0,0.095,40.0,104.0,NaN,0.0,NaN,48000.0,11/9/2007 12:00:00 AM,0.0,0.0,Regent Park,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
81,21022566.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5401.0,0.124,40.0,135.0,NaN,0.0,NaN,89000.0,10/10/2006 12:00:00 AM,0.0,0.0,Regent Park,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
82,21021965.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4025.0,0.092,35.0,115.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Franklin,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
83,21016503.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4713.0,0.108,40.0,118.0,NaN,0.0,NaN,5500.0,2/1/1975 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
84,21016385.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3833.0,0.088,35.0,110.0,NaN,0.0,NaN,2500.0,3/1/1987 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
85,21016345.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3850.0,0.088,35.0,110.0,NaN,0.0,NaN,16523.0,3/1/1983 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
86,21015573.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3354.0,0.077,30.0,112.0,NaN,0.0,NaN,3500.0,12/1/1988 12:00:00 AM,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
87,21015606.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4530.0,0.104,36.0,126.0,NaN,0.0,NaN,48000.0,9/1/2001 12:00:00 AM,0.0,0.0,Franklin,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
88,21066462.,0,402.0,RESIDENTIAL-VACANT,TAXABLE,5140.0,0.118,40.0,128.0,NaN,0.0,NaN,89307.0,10/15/2009 12:00:00 AM,600.0,586.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
89,21049879.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3815.0,0.088,35.0,109.0,NaN,0.0,NaN,69550.0,4/6/2011 12:00:00 AM,300.0,300.0,Chandler Park,00003,VACANT RESIDENTIAL,NaT,NaN,21049879.,2022-04-21,1000.0
90,21049352.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,0.084,30.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Riverbend,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
91,21049213.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,0.084,30.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Fox Creek,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
92,21075706.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5706.0,0.131,50.0,114.0,NaN,0.0,NaN,1000.0,4/8/2005 12:00:00 AM,0.0,0.0,Cornerstone Village,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
93,21075698.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5706.0,0.131,50.0,114.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,Cornerstone Village,00VAC,NaN,NaT,NaN,NaN,NaT,NaN
94,21075871.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6882.0,0.158,60.0,115.0,NaN,0.0,NaN,10000.0,10/1/1999 12:00:00 AM,0.0,0.0,Cornerstone Village,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
95,21073630.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6436.0,0.148,37.0,174.0,English Village North (H064),0.0,NaN,24900.0,11/29/2007 12:00:00 AM,0.0,0.0,East English Village,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
96,21076117.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,6882.0,0.158,60.0,114.0,NaN,0.0,NaN,1000.0,7/10/2008 12:00:00 AM,0.0,0.0,Cornerstone Village,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
97,21076388.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,6371.0,0.146,60.0,106.0,NaN,0.0,NaN,550000.0,5/9/2023 12:00:00 AM,500.0,500.0,Cornerstone Village,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
98,21065655.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4487.0,0.103,40.0,112.0,NaN,0.0,NaN,6000.0,1/19/2009 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
99,21065684.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4487.0,0.103,40.0,112.0,NaN,0.0,NaN,1750.0,6/30/2005 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
100,21049610.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3790.0,0.087,35.0,109.0,NaN,0.0,NaN,7500.0,8/1/1991 12:00:00 AM,0.0,0.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
101,21066941.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4792.0,0.110,40.0,120.0,NaN,0.0,NaN,6000.0,10/1/1985 12:00:00 AM,500.0,457.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,21066941.,2024-05-09,125.0
102,21066952.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4826.0,0.111,40.0,120.0,NaN,0.0,NaN,2250.0,10/13/2008 12:00:00 AM,500.0,500.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
103,21064633.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3807.0,0.087,30.0,122.0,NaN,0.0,NaN,4500.0,5/8/2013 12:00:00 AM,300.0,232.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
104,21065139.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,5321.0,0.122,45.0,119.0,Warren - Alter Rd (H060),0.0,NaN,46734.0,10/26/2006 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
105,21065232.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3720.0,0.085,30.0,124.0,Warren - Alter Rd (H060),0.0,NaN,15647.0,2/1/1992 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
106,21064501.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3398.0,0.078,30.0,114.0,Warren - Alter Rd (H060),0.0,NaN,3500.0,11/1/1974 12:00:00 AM,300.0,232.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
107,21064356.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),7179.0,0.165,63.0,114.0,NaN,0.0,NaN,50000.0,5/3/2002 12:00:00 AM,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN
108,21064276.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5480.0,0.126,35.0,167.0,NaN,0.0,NaN,45900.0,11/1/1999 12:00:00 AM,0.0,0.0,Morningside,00VAC,NaN,NaT,NaN,NaN,NaT,NaN

In [113]:
try3 = pd.merge(try2fix, policedf, how='left', left_on = 'Neighborhood', right_on='Neighborhood Name')

In [114]:
try3.head()

,Parcel ID,Taxpayer City,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Date Issued,Permit Status,parcelno,violation_date,fine_amount,Neighborhood Name,yearly_average
0,21019476.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,NaT,NaN,NaN,NaT,NaN,Franklin,1849.6
1,21019749.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN,Mapleridge,3387.6
2,21019245.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN,Mapleridge,3387.6
3,21019205.,1,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,Mapleridge,00VAC,NaN,NaT,NaN,NaN,NaT,NaN,Mapleridge,3387.6
4,21048771.,1,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,NaT,NaN,21048771.,2019-03-13,250.0,Riverbend,1610.6

In [115]:
try3["Year Built"].unique()

array([  nan, 1916., 2002., 1938., 1929., 1937., 1941., 1927., 1939.,
       1942., 1944., 1947., 1945., 1940., 1930., 1936., 1943., 1928.,
       1953., 1926., 1948., 1925., 1952., 1951., 1955., 1924., 2000.,
       2014., 1950., 1996., 1918., 1931., 1919., 1923., 1935., 1920.,
       1915., 1946., 1959., 1922., 1921., 1957., 1954., 1960., 1917.,
       1992., 1963., 1949., 1932., 1964., 1956., 1961., 1912., 1962.,
       1999., 2015., 1934., 2006., 2007., 1914., 1958., 1971., 1933.,
       1998., 1968., 1911., 1913., 1910., 2004., 1966., 1970., 1994.,
       1973., 2003., 1995., 1965., 2001., 2010., 1993., 1967., 2013.,
       1981., 2022., 1972., 1908., 2011., 1895., 2009., 1907., 2005.,
       1980., 2017., 1900., 1969., 1979., 1983., 1905., 1909., 1906.,
       1890., 1902., 1904., 1897., 1903., 1880., 1885., 1898., 1891.,
       1987., 1901., 2008., 1868., 1894., 1888., 1899., 1850., 1988.,
       1990., 1869., 1875., 2012., 1977., 1984., 1985., 1975., 1884.,
       1882., 1887., 2020., 1892., 1997., 1870., 1872., 1978., 1825.,
       2107., 2018., 2019., 1840., 1893., 1886., 1896., 1974., 1889.,
       2023., 1879., 1976., 1989., 1986., 1865., 1881., 1877., 1874.,
       1860., 1982., 1853., 1876., 1991., 1883., 2016., 1829., 1878.,
       1822., 2021.])

In [116]:
value_counts = try3["Property Class Description"].value_counts()
value_percentages = value_counts / len(try3) * 100
value_percentages

Property Class Description
RESIDENTIAL-IMPROVED    65.183015
RESIDENTIAL-VACANT      34.816985
Name: count, dtype: float64

In [117]:
#slimming down to residential_improved data (meaning it has a property on the lot)
residential_improved_count =(try3["Property Class Description"]=='RESIDENTIAL-IMPROVED').sum()
residential_improved_count

218221

In [118]:
#drop land without a resedencial structure on it
try3 = try3.drop(try3[(try3['Building Count'] == 0) & (try3['Property Class Description'] == 'RESIDENTIAL-VACANT')].index)
try3 = try3.drop(try3[(try3['Building Count'] == 0) & (try3['Property Class Description'] == 'RESIDENTIAL-IMPROVED')].index)
len(try3)

211975

In [119]:
#residential improved sttuctures count with a vacant residential sturuture on it
residential_improved_count =(try3["Property Class Description"]=='RESIDENTIAL-VACANT').sum()
residential_improved_count

57

In [120]:
try3.head()

,Parcel ID,Taxpayer City,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Date Issued,Permit Status,parcelno,violation_date,fine_amount,Neighborhood Name,yearly_average
239,21062470.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,3441.0,0.079,30.0,115.0,NaN,1.0,1916.0,65000.0,9/14/2021 12:00:00 AM,46200.0,16361.0,Jefferson Chalmers,41210,TWO FAMILY,NaT,NaN,21062470.,2024-04-16,250.0,Jefferson Chalmers,1602.2
266,21063979.,0,401.0,RESIDENTIAL-IMPROVED,TAXABLE,0.0,0.000,0.0,0.0,Warren - Alter Rd (H060),1.0,2002.0,13600.0,2/14/2014 12:00:00 AM,31700.0,12654.0,Morningside,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0
277,21068429.,0,401.0,RESIDENTIAL-IMPROVED,TAXABLE,5009.0,0.115,40.0,126.0,NaN,1.0,1938.0,79992.0,7/27/2023 12:00:00 AM,33400.0,15835.0,Moross-Morang,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Moross-Morang,3200.6
278,21069819.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4574.0,0.105,40.0,114.0,NaN,1.0,1929.0,8912.0,4/30/2010 12:00:00 AM,31300.0,13706.0,Morningside,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0
279,21070146.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4661.0,0.107,40.0,116.0,NaN,1.0,1938.0,20000.0,9/1/1987 12:00:00 AM,16200.0,8949.0,Outer Drive-Hayes,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Outer Drive-Hayes,4247.8

In [121]:
#importing in vacancy data
vacancy = pd.read_csv('/content/drive/MyDrive/detroit data/Vacant_Property_Registrations.csv')
vacancy = vacancy.rename(columns={"parcel_id": "Parcel ID"})
vacancy.head(10)
#parcelno

,X,Y,record_id,street_num,street_dir,street_name,date_status,address_id,Parcel ID,lon,lat,ObjectId
0,-9.254395e+06,5.217372e+06,VPO2010-03803,11626,NaN,YELLOWSTONE,2024/04/01 04:00:00+00,74606.0,14012633.,-83.133645,42.375352,1
1,-9.251294e+06,5.223992e+06,VPO2011-00161,17428,NaN,WOODWARD,2024/03/21 04:00:00+00,538386.0,01009693.,-83.105790,42.419267,2
2,-9.230812e+06,5.221026e+06,VPO2011-02997,3940,NaN,GUILFORD,2024/04/11 04:00:00+00,317717.0,21075610.,-82.921793,42.399594,3
3,-9.249232e+06,5.218158e+06,VPO2011-03556,751,NaN,CLAIRMOUNT,2022/05/04 04:00:00+00,344110.0,04002447.,-83.087269,42.380564,4
4,-9.263078e+06,5.227642e+06,VPO2011-05004,20543,NaN,FERGUSON,2023/04/05 04:00:00+00,73135.0,22063524.,-83.211644,42.443471,5
5,-9.264072e+06,5.212703e+06,VPO2011-05239,7264,NaN,FAUST,2023/09/21 04:00:00+00,161210.0,22078398.,-83.220578,42.344355,6
6,-9.250129e+06,5.208867e+06,VPO2011-06080,1601,NaN,CLARK,2023/12/19 05:00:00+00,178373.0,14010191.,-83.095327,42.318885,7
7,-9.251402e+06,5.218617e+06,VPO2011-06245,2005,NaN,LAWRENCE,2024/02/12 05:00:00+00,51115.0,08003328.,-83.106757,42.383611,8
8,-9.268162e+06,5.223484e+06,VPO2011-07779,17224,NaN,LAHSER,2023/09/13 04:00:00+00,390727.0,22113377.,-83.257316,42.415897,9
9,-9.249891e+06,5.216829e+06,VPO2011-09852,1612,W,EUCLID,2023/12/15 05:00:00+00,535612.0,08002127.,-83.093189,42.371747,10

In [124]:
#matched houses claimed to be residential imporved but are actually vacant according to the vacant dataset
column_name = 'Parcel ID'
matches = pd.Series(try3[column_name]).isin(vacancy[column_name])
count_matches = matches.sum()

print(f"Number of matching rows: {count_matches}")

Number of matching rows: 2591

In [125]:
#creating the vacant row in the main datset based on matches in previous cell
column_name = 'Parcel ID'
try3['vacant'] = try3[column_name].isin(vacancy[column_name]).astype(int)
try3.head()

,Parcel ID,Taxpayer City,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Date Issued,Permit Status,parcelno,violation_date,fine_amount,Neighborhood Name,yearly_average,vacant
239,21062470.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,3441.0,0.079,30.0,115.0,NaN,1.0,1916.0,65000.0,9/14/2021 12:00:00 AM,46200.0,16361.0,Jefferson Chalmers,41210,TWO FAMILY,NaT,NaN,21062470.,2024-04-16,250.0,Jefferson Chalmers,1602.2,0
266,21063979.,0,401.0,RESIDENTIAL-IMPROVED,TAXABLE,0.0,0.000,0.0,0.0,Warren - Alter Rd (H060),1.0,2002.0,13600.0,2/14/2014 12:00:00 AM,31700.0,12654.0,Morningside,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0,0
277,21068429.,0,401.0,RESIDENTIAL-IMPROVED,TAXABLE,5009.0,0.115,40.0,126.0,NaN,1.0,1938.0,79992.0,7/27/2023 12:00:00 AM,33400.0,15835.0,Moross-Morang,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Moross-Morang,3200.6,0
278,21069819.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4574.0,0.105,40.0,114.0,NaN,1.0,1929.0,8912.0,4/30/2010 12:00:00 AM,31300.0,13706.0,Morningside,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0,0
279,21070146.,1,401.0,RESIDENTIAL-IMPROVED,TAXABLE,4661.0,0.107,40.0,116.0,NaN,1.0,1938.0,20000.0,9/1/1987 12:00:00 AM,16200.0,8949.0,Outer Drive-Hayes,41110,SINGLE FAMILY,NaT,NaN,NaN,NaT,NaN,Outer Drive-Hayes,4247.8,0

In [132]:
#propety with vacant house in the main dataset
#not usre why its y7 less than expected from the matches but close
vacancy_house = ((try3["Building Count"] == 1) & (try3['vacant'] == 1)).sum()
print(vacancy_house)

2584