In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### BUILDING PERMITS

In [14]:
#importing in bulding permit data
building_permits = pd.read_csv('/content/drive/MyDrive/detroit data/building_permits_2023_5461986780762354220.csv')
building_permits.head(100)

,Record ID,Street Number,Street Direction,Street Name,Street Type,Date Submitted,Date Issued,Permit Status,Permit Payment Amount,Building Legal Use,Stories,Zoning Code,Proposed Use,Type of Construction,Permit Type,Description of Work,Contractor Estimated Cost,Department Estimated Cost,Parcel ID,Latitude,Longitude,ObjectId,Address ID,Open to Elements?,Missing Portions?,Purchased From DLBA?,DLBA Compliant?,Change in Units?,Vacant?,x,y
0,BLD2010-03399,14401,NaN,PIERSON,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22107015.,42.392052,-83.246171,1,545664.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.266921e+06,5.219889e+06
1,BLD2010-03740,16153,NaN,PATTON,NaN,7/20/2020 12:00:00 AM,7/20/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22104480.,42.408558,-83.244342,2,119289.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.266718e+06,5.222377e+06
2,BLD2011-04453,19818,NaN,TRACEY,NaN,6/10/2020 12:00:00 AM,6/10/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22031544.003L,42.438097,-83.181656,3,21111.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.259740e+06,5.226832e+06
3,BLD2012-04426,18014,NaN,WARRINGTON,NaN,11/5/2020 12:00:00 AM,11/5/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02003998.,42.422898,-83.139332,4,236621.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.255028e+06,5.224540e+06
4,BLD2012-05925,14025,NaN,WOODROW WILSON,NaN,9/16/2020 12:00:00 AM,9/16/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.401645,-83.114097,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9.252219e+06,5.221335e+06
5,BLD2013-02178,18924,NaN,PARKSIDE,NaN,7/16/2020 12:00:00 AM,7/16/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02002914.,42.429993,-83.131915,6,309841.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.254202e+06,5.225610e+06
6,BLD2013-03057,9300,W,JEFFERSON,NaN,5/14/2021 12:00:00 AM,5/14/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20000089.,42.284677,-83.125332,7,254180.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.253470e+06,5.203719e+06
7,BLD2013-03830,1478,NaN,BALDWIN,NaN,10/28/2020 12:00:00 AM,10/28/2020 12:00:00 AM,Issued,NaN,TWO FAMILY DWELLING,1.0,R2-Two Family Residential,ONE FAMILY DWELLING,5B - COMBUSTIBLE (FP 000),Change of Use,CHANGE FROM TWO FAM TO ONE FAM,10000.0,NaN,17011093.,42.354929,-83.000980,8,330194.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.239627e+06,5.214295e+06
8,BLD2014-00030,2501,NaN,RUSSELL,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05003453-0,42.345972,-83.040569,9,258803.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.244034e+06,5.212946e+06
9,BLD2014-01792,16543,NaN,MEYERS,NaN,8/13/2020 12:00:00 AM,8/13/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22020220-7,42.412719,-83.170223,10,88587.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.258467e+06,5.223005e+06
10,BLD2014-01920,2457,NaN,RUSSELL AKA 2453-69 RUSSELL,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05003456-60,42.345385,-83.040253,11,255158.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.243999e+06,5.212858e+06
11,BLD2014-02219,13131,NaN,LYNDON,NaN,2/19/2021 12:00:00 AM,2/19/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22029857.006L,42.394396,-83.174945,12,537316.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.258993e+06,5.220242e+06
12,BLD2014-02276,17301,NaN,WESTMORELAND,NaN,1/6/2021 12:00:00 AM,1/6/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22093452.,42.417618,-83.236441,13,112066.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.265838e+06,5.223743e+06
13,BLD2014-02445,20534,NaN,BRAILE,NaN,1/5/2021 12:00:00 AM,1/5/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22105488.019,42.442520,-83.246348,14,96667.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.266941e+06,5.227499e+06
14,BLD2014-02447,12001,NaN,BEAVERLAND,NaN,1/5/2021 12:00:00 AM,1/5/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22118702-4,42.374108,-83.264867,15,174144.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.269003e+06,5.217185e+06
15,BLD2014-02450,21231,NaN,PEMBROKE,NaN,1/26/2021 12:00:00 AM,1/26/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22017857.,42.436261,-83.251954,16,98257.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.267565e+06,5.226555e+06
16,BLD2014-02725,22162,NaN,HESSEL,NaN,3/31/2021 12:00:00 AM,3/31/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22018541.002,42.441327,-83.260963,17,104949.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.268568e+06,5.227319e+06
17,BLD2014-02736,22761,NaN,CAMBRIDGE,NaN,1/5/2021 12:00:00 AM,1/5/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22119372.032L,42.429898,-83.266755,18,106985.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.269213e+06,5.225595e+06
18,BLD2014-02766,11300,NaN,PENROD,NaN,2/6/2020 12:00:00 AM,2/6/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22077686-7,42.369914,-83.220096,19,185767.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.264019e+06,5.216553e+06
19,BLD2014-03099,8801,NaN,SCHAEFER,NaN,1/15/2021 12:00:00 AM,1/15/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22031150.,42.358855,-83.178509,20,216171.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.259389e+06,5.214887e+06
20,BLD2014-03257,733,NaN,ST ANTOINE,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03003407-15,42.334310,-83.040456,21,11080.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.244021e+06,5.211190e+06
21,BLD2014-03674,901,W,LAFAYETTE,NaN,1/23/2020 12:00:00 AM,1/23/2020 12:00:00 AM,Issued,NaN,cell tower,1.0,M4-Intensive Industrial,cell tower,NaN,New,NaN,20000.0,NaN,04000122-3,42.327430,-83.056927,22,287374.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.245855e+06,5.210154e+06
22,BLD2014-04028,16576,NaN,GREENLAWN,NaN,3/13/2020 12:00:00 AM,3/13/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16029427.,42.413412,-83.150751,23,85400.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.256299e+06,5.223109e+06
23,BLD2014-04789,15800,NaN,TIREMAN,NaN,11/30/2020 12:00:00 AM,11/30/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22001841.001,42.351352,-83.199843,24,351915.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.261764e+06,5.213756e+06
24,BLD2014-04939,10832,NaN,PURITAN,NaN,8/17/2020 12:00:00 AM,8/17/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16007653-7,42.409880,-83.169409,25,88674.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.258376e+06,5.222577e+06
25,BLD2014-05006,8597,NaN,SOUTHFIELD,NaN,11/30/2020 12:00:00 AM,11/30/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22074514.,42.356150,-83.216906,26,481049.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.263664e+06,5.214479e+06
26,BLD2014-05179,18712,NaN,FAUST,NaN,11/30/2020 12:00:00 AM,11/30/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22078795.,42.428439,-83.223822,27,117516.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.264433e+06,5.225375e+06
27,BLD2014-05241,19810,NaN,TRINITY,NaN,11/30/2020 12:00:00 AM,11/30/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22108648.004,42.436368,-83.249836,28,98303.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.267329e+06,5.226571e+06
28,BLD2014-05790,8100,NaN,NORMILE,NaN,1/28/2020 12:00:00 AM,1/28/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18016409.,42.353196,-83.158454,29,192503.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.257157e+06,5.214034e+06
29,BLD2014-05864,23841,NaN,GRAND RIVER,NaN,11/30/2020 12:00:00 AM,11/30/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22007520-34,42.423717,-83.276276,30,353302.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.270273e+06,5.224663e+06
30,BLD2015-00616,3031,NaN,MONTGOMERY,NaN,9/9/2021 12:00:00 AM,9/9/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12001610.,42.363003,-83.108122,31,82031.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.251554e+06,5.215512e+06
31,BLD2015-00817,97,NaN,DELAWARE,NaN,1/23/2020 12:00:00 AM,1/23/2020 12:00:00 AM,Issued,NaN,one family dwelling,3.0,R1-Single-Family Residential,one family dwelling,5B - COMBUSTIBLE (FP 000),Alteration,repairs,15000.0,NaN,02001168.,42.373317,-83.077537,32,340585.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.248149e+06,5.217066e+06
32,BLD2015-00821,8568,NaN,CHEYENNE,NaN,7/23/2020 12:00:00 AM,7/23/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22025571.,42.357334,-83.173460,33,194277.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.258827e+06,5.214658e+06
33,BLD2015-00910,18055,NaN,GREENFIELD,NaN,9/25/2020 12:00:00 AM,9/25/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22050691-5,42.422102,-83.199933,34,63679.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.261774e+06,5.224419e+06
34,BLD2015-00943,6511,NaN,EPWORTH,NaN,3/29/2019 12:00:00 AM,3/29/2019 12:00:00 AM,Issued,NaN,Storage & Warehouse,NaN,M4-Intensive Industrial,Outdoors Storage,5A - COMBUSTIBLE (FP 111),Alteration,ESTABLISH AN OPEN OUTDOOR STORAGE OF EQUIPMENT...,NaN,NaN,16014954.,42.350262,-83.129026,35,490237.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.253881e+06,5.213592e+06
35,BLD2015-00965,20644,NaN,TIREMAN,NaN,1/21/2020 12:00:00 AM,1/21/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22001605.,42.350420,-83.242637,36,170759.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.266528e+06,5.213616e+06
36,BLD2015-00966,9630,NaN,TERRY,NaN,1/16/2020 12:00:00 AM,1/16/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22042842.,42.367413,-83.190544,37,204837.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.260729e+06,5.216176e+06
37,BLD2015-01189,2161,NaN,HURLBUT,NaN,1/22/2020 12:00:00 AM,1/22/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19004860.,42.365760,-82.984050,38,334091.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.237742e+06,5.215927e+06
38,BLD2015-01378,770,NaN,CONNER,NaN,8/17/2020 12:00:00 AM,8/17/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21046017.,42.366048,-82.956176,39,339275.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.234639e+06,5.215970e+06
39,BLD2015-02145,10832,NaN,PURITAN,NaN,8/17/2020 12:00:00 AM,8/17/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16007653-7,42.409880,-83.169409,40,88674.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.258376e+06,5.222577e+06
40,BLD2015-02444,620,NaN,WOODWARD,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01004102-3,42.330752,-83.045703,41,348076.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.244605e+06,5.210654e+06
41,BLD2015-02999,8251,NaN,NORTHLAWN,NaN,1/28/2020 12:00:00 AM,1/28/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18014836.,42.355027,-83.152037,42,189371.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.256442e+06,5.214310e+06
42,BLD2015-03004,20216,NaN,FENTON,NaN,9/24/2020 12:00:00 AM,9/24/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22123715.014,42.439093,-83.282463,43,103930.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.270961e+06,5.226982e+06
43,BLD2015-03023,14060,NaN,JOS CAMPAU,NaN,11/19/2020 12:00:00 AM,11/19/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,09011351-3,42.419039,-83.072265,44,467781.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.247562e+06,5.223958e+06
44,BLD2015-03076,1807,NaN,LIVERNOIS,NaN,1/29/2020 12:00:00 AM,1/29/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18007124.,42.314979,-83.109992,45,153900.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.251762e+06,5.208279e+06
45,BLD2015-03295,1404,NaN,LONGFELLOW,NaN,8/10/2020 12:00:00 AM,8/10/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06002511.,42.381223,-83.095703,46,50951.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.250171e+06,5.218257e+06
46,BLD2015-03317,9196,NaN,AVIS,NaN,1/22/2020 12:00:00 AM,1/22/2020 12:00:00 AM,Issued,NaN,twofamily,1.0,R2-Two Family Residential,two family,5B - COMBUSTIBLE (FP 000),Alteration,roofrepair,7559.0,7559.0,20003291.,42.303229,-83.134538,47,48018.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.254494e+06,5.206510e+06
47,BLD2015-03565,1001,NaN,WOODWARD,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02001892.,42.331992,-83.047583,48,28522.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.244815e+06,5.210841e+06
48,BLD2015-05274,17321,NaN,STRATHMOOR,NaN,2/28/2020 12:00:00 AM,2/28/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22038245.,42.418670,-83.188787,49,66095.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.260533e+06,5.223902e+06
49,BLD2015-05373,2112,NaN,MICHIGAN,NaN,10/18/2021 12:00:00 AM,10/18/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000296-7,42.331659,-83.075514,50,239158.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.247924e+06,5.210791e+06
50,BLD2015-05946,3862,NaN,IROQUOIS,NaN,1/28/2020 12:00:00 AM,1/28/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17007074.,42.370734,-83.003444,51,346915.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.239901e+06,5.216676e+06
51,BLD2015-06042,18400,NaN,ASHTON,NaN,1/6/2020 12:00:00 AM,1/6/2020 12:00:00 AM,Issued,NaN,ONE FAMILY DWELLING,1.0,R1-Single-Family Residential,ONE FAMILY DWELLING,5B - COMBUSTIBLE (FP 000),Alteration,FIRE REPAIRS AS PER ATTACHED SCOPE OF WORK. OB...,13400.0,NaN,22075187.,42.425024,-83.219997,52,117811.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.264008e+06,5.224860e+06
52,BLD2015-06329,5421,W,OUTER DRIVE,NaN,7/14/2020 12:00:00 AM,7/14/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22125257.,42.424731,-83.174799,53,21648.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.258976e+06,5.224816e+06
53,BLD2015-06341,4779,NaN,GLENDALE,NaN,1/17/2020 12:00:00 AM,1/17/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14005058.,42.383039,-83.138443,54,77516.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.254929e+06,5.218531e+06
54,BLD2015-06993,611,NaN,WOODWARD AVENUE,NaN,7/23/2020 12:00:00 AM,7/23/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02001894-9,42.330441,-83.046646,55,295845.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.244710e+06,5.210607e+06
55,BLD2015-07110,3676,NaN,LIVERNOIS,NaN,1/23/2020 12:00:00 AM,1/23/2020 12:00:00 AM,Issued,NaN,single family,1.0,B2-Local Business & Residential,single family,NaN,Alteration,NaN,20000.0,NaN,16017138.,42.328649,-83.118077,56,428609.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.252662e+06,5.210337e+06
56,BLD2015-07213,9557,NaN,SOUTHFIELD,NaN,10/21/2020 12:00:00 AM,10/21/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57,548943.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,BLD2015-07421,16502,NaN,KENTUCKY,NaN,2/25/2020 12:00:00 AM,2/25/2020 12:00:00 AM,Issued,NaN,MULTI FAMILY,2.0,R1-Single-Family Residential,MULTI FAMILY,5B - COMBUSTIBLE (FP 000),Alteration,INSTALL 20 VINYL REPLACEMENT WINDOWS AT 16502 ...,13000.0,NaN,16036564.,42.412281,-83.158763,58,98229.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.257191e+06,5.222939e+06
58,BLD2015-07670,6905,NaN,WARWICK,NaN,9/21/2020 12:00:00 AM,9/21/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22086727.,42.342506,-83.227010,59,160108.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.264788e+06,5.212424e+06
59,BLD2015-07916,16840,NaN,FAIRFIELD,NaN,11/30/2020 12:00:00 AM,11/30/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12012112.,42.415496,-83.134864,60,27511.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.254531e+06,5.223423e+06
60,BLD2015-07964,20348,NaN,REDFERN,NaN,3/11/2020 12:00:00 AM,3/11/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22117056.015,42.441641,-83.264916,61,104998.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.269008e+06,5.227366e+06
61,BLD2015-08106,15310,NaN,IDAHO,NaN,7/12/2021 12:00:00 AM,7/12/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.403578,-83.116818,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9.252522e+06,5.221626e+06
62,BLD2015-08236,15850,NaN,STRATHMOOR,NaN,6/22/2020 12:00:00 AM,6/22/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22012056.,42.408454,-83.186785,63,141142.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.260311e+06,5.222362e+06
63,BLD2015-08419,11750,NaN,PLEASANT,NaN,1/14/2020 12:00:00 AM,1/14/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20017708.001,42.281113,-83.140209,64,496546.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.255126e+06,5.203182e+06
64,BLD2015-08543,12645,W,OUTER DRIVE,NaN,8/17/2020 12:00:00 AM,8/17/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22124731-7,42.383056,-83.257539,65,543981.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.268187e+06,5.218533e+06
65,BLD2016-00029,2465,NaN,CHICAGO,NaN,9/2/2021 12:00:00 AM,9/2/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10002695.,42.376942,-83.108928,66,38944.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.251644e+06,5.217612e+06
66,BLD2016-00043,6025,NaN,EPWORTH,NaN,7/31/2020 12:00:00 AM,7/31/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16014989.,42.346101,-83.125911,67,177688.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.253534e+06,5.212966e+06
67,BLD2016-00079,1330,NaN,PLUM,NaN,7/31/2020 12:00:00 AM,7/31/2020 12:00:00 AM,Issued,NaN,CELL TOWER,0.0,B4-General Business,CELL TOWER,1A - CONC/STL (FP 443),Alteration,MODIFICATIONS TO EXISTING ROOFTOP CELL FACILIT...,10000.0,NaN,NaN,NaN,NaN,68,549063.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,BLD2016-00133,1,NaN,WOODWARD,NaN,7/31/2020 12:00:00 AM,7/31/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02001910-5,42.328900,-83.045469,69,290672.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.244579e+06,5.210375e+06
69,BLD2016-00134,14963,NaN,PENROD,NaN,7/31/2020 12:00:00 AM,7/31/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22077882.,42.398422,-83.221926,70,125732.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.264222e+06,5.220849e+06
70,BLD2016-00215,17675,NaN,STAHELIN,NaN,8/26/2020 12:00:00 AM,8/26/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22083512.,42.421586,-83.227399,71,118472.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.264832e+06,5.224342e+06
71,BLD2016-00296,17513,NaN,WISCONSIN,NaN,9/15/2020 12:00:00 AM,9/15/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16035108.,42.420848,-83.157566,72,19824.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.257058e+06,5.224230e+06
72,BLD2016-00298,17513,NaN,WISCONSIN,NaN,9/15/2020 12:00:00 AM,9/15/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16035108.,42.420848,-83.157566,73,19824.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.257058e+06,5.224230e+06
73,BLD2016-00603,18291,NaN,STANSBURY,NaN,3/11/2020 12:00:00 AM,3/11/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22033806.,42.425086,-83.183997,74,67561.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.260000e+06,5.224869e+06
74,BLD2016-00608,1378,NaN,MICHIGAN,NaN,1/29/2020 12:00:00 AM,1/29/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06000411.,42.331719,-83.065440,75,545759.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.246802e+06,5.210800e+06
75,BLD2016-00674,17421,NaN,CHERRYLAWN,NaN,7/27/2020 12:00:00 AM,7/27/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16033264.,42.420511,-83.155327,76,13171.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.256809e+06,5.224180e+06
76,BLD2016-00726,16853,NaN,LOG CABIN,NaN,1/25/2021 12:00:00 AM,1/25/2021 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,08009561.,42.415880,-83.122134,77,538265.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.253114e+06,5.223481e+06
77,BLD2016-00867,5824,NaN,LAWNDALE,NaN,2/7/2020 12:00:00 AM,7/24/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20006314.,42.334676,-83.151936,78,215017.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.256431e+06,5.211245e+06
78,BLD2016-00929,17127,NaN,KENTUCKY,NaN,12/21/2020 12:00:00 AM,12/21/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16036957.,42.417443,-83.159523,79,15050.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.257276e+06,5.223717e+06
79,BLD2016-00947,7789,NaN,WHITTAKER,NaN,1/14/2020 12:00:00 AM,1/14/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20004088.,42.311165,-83.125304,80,35841.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.253467e+06,5.207705e+06
80,BLD2016-01037,7108,NaN,THATCHER,NaN,9/23/2020 12:00:00 AM,9/23/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16008309.,42.422793,-83.143475,81,10028.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.255489e+06,5.224524e+06
81,BLD2016-01100,15004,NaN,WARWICK,NaN,9/9/2020 12:00:00 AM,9/9/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22086046.,42.398516,-83.228448,82,125180.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.264948e+06,5.220863e+06
82,BLD2016-01326,15322,NaN,SORRENTO,NaN,3/11/2020 12:00:00 AM,3/11/2020 12:00:00 AM,Issued,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22023567.,42.402662,-83.172281,83,93588.0,NaN,NaN,NaN,NaN,NaN,NaN,-9.258696e+06,5.221488e+06

In [15]:
#parcel id date and permit are the only columns needed for now
columns_to_keep = ['Parcel ID', 'Date Issued', 'Permit Status']
building_permits_1 = building_permits[columns_to_keep]

building_permits_1.head(1)

   Parcel ID            Date Issued Permit Status
0  22107015.  7/27/2020 12:00:00 AM        Issued

### BLIGHT VIOLATIONS

In [16]:
#importing in blight violation data
blight_violations = pd.read_csv('/content/drive/MyDrive/detroit data/blight_violations (1).csv')
blight_violations.head(1)
#parcelno

<ipython-input-16-db77d960083b>:2: DtypeWarning: Columns (8,10,15,16,17,37) have mixed types. Specify dtype option on import or set low_memory=False.
  blight_violations = pd.read_csv('/content/drive/MyDrive/detroit data/blight_violations (1).csv')

,ticket_id,ticket_number,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_address,violation_zip_code,violator_id,mailing_address_street_number,mailing_address_street_name,mailing_address,city,state,zip_code,non_us_str_code,country,violation_date,ticket_issued_time,hearing_date,hearing_time,judgment_date,ordinance_law,ordinance_description,disposition,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,parcelno,longitude,latitude,address_id,updated_at,ESRI_OID
0,19939,05002662DAH,"Buildings, Safety Engineering & Env Department",Joseph Otis,PRESTIGE CLEANERS,660,WOODWARD AVE,660 WOODWARD AVE,NaN,2523,660,WOODWARD,660 WOODWARD,DETROIT,MI,48226,NaN,NaN,1107216000000,1727173800000,1.111018e+12,10:30AM,1.111450e+12,9-1-36(a),Failure of owner to obtain certificate of comp...,Responsible,250.0,20,10,0.0,0.0,NaN,280.0,0.0,280.0,NaN,NO PAYMENT APPLIED,NaN,01004105.,-83.04554,42.33103,348114.0,1111498938263,1

In [17]:
# parcelno, date, fine amount are the only ones needed
columns_to_keep = ['parcelno', 'violation_date', 'fine_amount']
blight_violations_1 = blight_violations[columns_to_keep]

blight_violations_1.head(1)

    parcelno  violation_date  fine_amount
0  01004105.   1107216000000        250.0

In [18]:
#dropping N/A's
blight_violations_1 = blight_violations_1[blight_violations_1['violation_date'].notna()]
blight_violations_1 = blight_violations_1[blight_violations_1['parcelno'].notna()]
blight_violations_1 = blight_violations_1[blight_violations_1['fine_amount'].notna()]

In [19]:
#filter out all rows where violation_date is not 13-those must have been inputted incorrectly and will not convert to readable date correclty theres only 23 of them
blight_violations_1['violation_date'] = blight_violations_1['violation_date'].astype(str)

blight_violations_1 = blight_violations_1[blight_violations_1['violation_date'].str.isdigit() & (blight_violations_1['violation_date'].str.len() == 13)]

len(blight_violations_1)

727975

In [20]:
#now we have to convert the unix timestamp in the violation_date to a readbable date (using ms) becuase its 13 digits i think
blight_violations_1['violation_date'] = pd.to_datetime(blight_violations_1['violation_date'], unit='ms')

blight_violations_1.head()

<ipython-input-20-c037620e16f7>:2: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  blight_violations_1['violation_date'] = pd.to_datetime(blight_violations_1['violation_date'], unit='ms')

      parcelno violation_date  fine_amount
0    01004105.     2005-02-01        250.0
1    22055135.     2005-01-31        100.0
2    22055131.     2005-01-31        100.0
3  22029963-72     2005-01-28        100.0
4    22054318.     2005-01-31        100.0

In [21]:
#####

In [22]:
# parcels = pd.read_csv('C:/Users/mhviz/mlb-fast-prop/detroit_housing_data.gitignore/Parcels.csv', low_memory = False)
# parcels.head(1)
# #parcel_number

In [23]:
# #changing building_permits parcel id to parcel_number

# building_permits = building_permits.rename(columns={"Parcel ID": "parcel_number"})

In [24]:
# #changing blight_violations parcelno to parcel_number

# blight_violations = blight_violations.rename(columns={"parcelno": "parcel_number"})
# blight_violations.head()

In [25]:
# #merging building_permits and blight_violations
# merged_permits_and_violations = pd.merge(building_permits, blight_violations, on='parcel_number')

# merged_permits_and_violations.len()

### PARCELS

In [26]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np

In [27]:
parcels = pd.read_csv('/content/drive/MyDrive/detroit data/parcel_file_current_3346032144909824368.csv', low_memory = False)
parcels.head(10)

,object_id,Parcel ID,Address,ZIP Code,Taxpayer 1,Taxpayer 2,Taxpayer Address,Taxpayer City,Taxpayer State,Taxpayer ZIP Code,Property Class,Property Class Description,Previous Property Class,Use Code,Use Code Description,Zoning District,Year Built,Building Style,Building Count,Total Floor Area,Tax Status,Tax Status Description,Previous Tax Status,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Principal Residence Exemption % Claimed,NEZ District,ECF Neighborhood,Is Improved,Related Parcel ID,Sale Date,Sale Price,Total Square Footage,Total Acreage,Frontage,Depth,Parcel Modified Date,Legal Description,Ward,Landmap,Subdivision,Local Historic District,Neighborhood,Council District,Street Number,Street Prefix,Street Name,ObjectId,Shape__Area,Shape__Length
0,24265600,21019476.,13702 EASTWOOD,48205,"BOOKER, TRANYSSA",NaN,13667 SARATOGA,DETROIT,MI,48205,402.0,RESIDENTIAL-VACANT,402.0,00003,VACANT RESIDENTIAL,R2,NaN,NaN,0.0,NaN,TAXABLE,TAXABLE,TAXABLE,400.0,400.0,400.0,400.0,0.0,NaN,3R321,0.0,NaN,NaN,0.0,4617.0,0.106,35.0,131.0,NaN,Property exempt from Ad Valorem taxes and asse...,21.0,539,NaN,NaN,Franklin,3.0,13702.0,NaN,EASTWOOD,1,786.476562,137.760108
1,24276382,21019749.,14802 FORDHAM,48205,DETROIT LAND BANK AUTHORITY,NaN,"500 GRISWOLD STREET, SUITE 1200",DETROIT,MI,48226,402.0,RESIDENTIAL-VACANT,402.0,00VAC,NaN,R1,NaN,NaN,0.0,NaN,EXEMPT (211.7GG),PROPERTY HELD BY LAND BANK FAST TRACK AUTHORITY,EXEMPT (211.7GG),0.0,0.0,0.0,0.0,0.0,NaN,4R402,0.0,NaN,10/19/2012 12:00:00 AM,915.0,4312.0,0.099,42.0,103.0,NaN,S FORDHAM 93 YOUNGS GRATIOT VIEW SUB ANNEX L41...,21.0,544,NaN,NaN,Mapleridge,4.0,14802.0,NaN,FORDHAM,2,735.906250,119.853863
2,24276199,21019245.,15109 SARATOGA,48205,DETROIT LAND BANK AUTHORITY,NaN,"500 GRISWOLD STREET, SUITE 1200",DETROIT,MI,48226,402.0,RESIDENTIAL-VACANT,402.0,00VAC,NaN,R1,NaN,NaN,0.0,NaN,EXEMPT (211.7GG),PROPERTY HELD BY LAND BANK FAST TRACK AUTHORITY,EXEMPT (211.7GG),0.0,0.0,0.0,0.0,0.0,NaN,4R402,0.0,NaN,8/1/1991 12:00:00 AM,18000.0,3605.0,0.083,35.0,103.0,NaN,N SARATOGA 212 YOUNGS GRATIOT VIEW SUB ANNEX L...,21.0,544,NaN,NaN,Mapleridge,4.0,15109.0,NaN,SARATOGA,3,616.484375,114.194160
3,24362721,21019205.,14651 SARATOGA,48205,DETROIT LAND BANK AUTHORITY,NaN,"500 GRISWOLD STREET, SUITE 1200",DETROIT,MI,48226,402.0,RESIDENTIAL-VACANT,402.0,00VAC,NaN,R1,NaN,NaN,0.0,NaN,EXEMPT (211.7GG),PROPERTY HELD BY LAND BANK FAST TRACK AUTHORITY,EXEMPT (211.7GG),0.0,0.0,0.0,0.0,0.0,NaN,4R402,0.0,NaN,4/1/1982 12:00:00 AM,13168.0,3399.0,0.078,33.0,103.0,7/11/2019 12:00:00 AM,N SARATOGA E 33.25 FT 24 ELITE GARDENS SUB L41...,21.0,544,NaN,NaN,Mapleridge,4.0,14651.0,NaN,SARATOGA,4,586.628906,113.012217
4,24260532,21048771.,2231 GRAY,48215,1 MONTCLAIR LLC,NaN,5302 BURNS,DETROIT,MI,48213,402.0,RESIDENTIAL-VACANT,402.0,00003,VACANT RESIDENTIAL,R2,NaN,NaN,0.0,NaN,TAXABLE,TAXABLE,TAXABLE,600.0,600.0,600.0,600.0,0.0,NaN,4R418,0.0,NaN,4/1/2000 12:00:00 AM,2620.0,3746.0,0.086,31.0,121.0,NaN,PROPERTY EXEMPT FROM AD VALOREM TAXES AND ASSE...,21.0,530,NaN,NaN,Riverbend,4.0,2231.0,NaN,GRAY,5,642.500000,126.087382
5,24247992,21042930-1,3889 LILLIBRIDGE,48214,"BAILEY, ABAYOMI",NaN,3895 LILLIBRIDGE,DETROIT,MI,48214,402.0,RESIDENTIAL-VACANT,402.0,00003,VACANT RESIDENTIAL,R2,NaN,NaN,0.0,NaN,TAXABLE,TAXABLE,TAXABLE,300.0,300.0,300.0,300.0,0.0,NaN,4R419,0.0,NaN,NaN,0.0,3049.0,0.070,30.0,102.0,NaN,Property exempt from Ad Valorem taxes and asse...,21.0,500,NaN,NaN,West End,4.0,3889.0,NaN,LILLIBRIDGE,6,520.660156,108.838861
6,24357117,21042799.,4608 LILLIBRIDGE,48213,"MALLARD, SCOTT",NaN,4608 LILLIBRIDGE,DETROIT,MI,48213,402.0,RESIDENTIAL-VACANT,402.0,00003,VACANT RESIDENTIAL,R2,NaN,NaN,0.0,NaN,TAXABLE,TAXABLE,EXEMPT (211.7GG),0.0,0.0,0.0,0.0,0.0,NaN,4R419,0.0,NaN,8/21/2007 12:00:00 AM,49500.0,3311.0,0.076,32.0,103.0,6/7/2019 12:00:00 AM,E LILLIBRIDGE 43 HANS A CHRISTIANSENS SUB L30 ...,21.0,501,NaN,NaN,West End,4.0,4608.0,NaN,LILLIBRIDGE,7,561.675781,111.392391
7,24260820,21047341.,4658 ANDERDON,48215,DETROIT LAND BANK AUTHORITY,NaN,"500 GRISWOLD STREET, SUITE 1200",DETROIT,MI,48226,402.0,RESIDENTIAL-VACANT,402.0,00VAC,NaN,R2,NaN,NaN,0.0,NaN,EXEMPT (211.7GG),PROPERTY HELD BY LAND BANK FAST TRACK AUTHORITY,EXEMPT (211.7GG),0.0,0.0,0.0,0.0,0.0,NaN,4R416,0.0,NaN,7/1/1971 12:00:00 AM,14000.0,3660.0,0.084,30.0,122.0,NaN,61 of 2003 expiring 12/31/2010. Property asse...,21.0,532,NaN,NaN,Fox Creek,4.0,4658.0,NaN,ANDERDON,8,625.394531,125.556045
8,24260010,21047551.,4861 MAYNARD,48215,DETROIT LAND BANK AUTHORITY,NaN,"500 GRISWOLD STREET, SUITE 1200",DETROIT,MI,48226,402.0,RESIDENTIAL-VACANT,402.0,00VAC,NaN,R2,NaN,NaN,0.0,NaN,EXEMPT (211.7GG),PROPERTY HELD BY LAND BANK FAST TRACK AUTHORITY,EXEMPT (211.7GG),0.0,0.0,0.0,0.0,0.0,NaN,4R416,0.0,NaN,10/1/1981 12:00:00 AM,7300.0,4792.0,0.110,40.0,120.0,NaN,W MAYNARD 26 JEFFERSON PARK LAND CO LTD SUB L4...,21.0,532,NaN,NaN,Fox Creek,4.0,4861.0,NaN,MAYNARD,9,819.691406,132.120570
9,24260414,21047578.,2188 SPRINGLE,48215,DETROIT LAND BANK AUTHORITY,NaN,"500 GRISWOLD STREET, SUITE 1200",DETROIT,MI,48226,402.0,RESIDENTIAL-VACANT,402.0,00VAC,NaN,R2,NaN,NaN,0.0,NaN,EXEMPT (211.7GG),PROPERTY HELD BY LAND BANK FAST TRACK AUTHORITY,EXEMPT (211.7GG),0.0,0.0,0.0,0.0,0.0,NaN,4R418,0.0,NaN,NaN,0.0,4270.0,0.098,35.0,122.0,NaN,E SPRINGLE 210 DANIEL J CAMPAUS SUB L29 P44 PL...,21.0,530,NaN,NaN,Riverbend,4.0,2188.0,NaN,SPRINGLE,10,728.113281,129.579645

In [28]:
print(parcels['Council District'].value_counts())  # For categorical data

Council District
3.0     59397
4.0     55835
5.0     54685
7.0     54343
6.0     52441
1.0     51814
2.0     50880
0.0        21
11.0        1
22.0        1
Name: count, dtype: int64

In [29]:
parcels1 = parcels[["Parcel ID",
                    "Taxpayer City",
                    "Taxpayer 1",
                    "Property Class",
                    "Property Class Description",
                    "Tax Status",
                    "Total Square Footage",
                    "Total Floor Area",
                    "Total Acreage",
                    "Frontage",
                    "Depth",
                    "NEZ District",
                    "Building Count",
                    "Year Built",
                    "Sale Price",
                    "Sale Date",
                    "Previous Assessed Value",
                    "Assessed Value",
                    "Taxable Value",
                    "Previous Taxable Value",
                    "Neighborhood",
                    "Use Code",
                    "Use Code Description",
                    "Council District",
                    ]]
parcels2 = parcels1[parcels1["Property Class"].isin([401,402])]
parcels2.head(10)

,Parcel ID,Taxpayer City,Taxpayer 1,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Floor Area,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Council District
0,21019476.,DETROIT,"BOOKER, TRANYSSA",402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,NaN,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,3.0
1,21019749.,DETROIT,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,NaN,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0
2,21019245.,DETROIT,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,NaN,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0
3,21019205.,DETROIT,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,NaN,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0
4,21048771.,DETROIT,1 MONTCLAIR LLC,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,NaN,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,4.0
5,21042930-1,DETROIT,"BAILEY, ABAYOMI",402.0,RESIDENTIAL-VACANT,TAXABLE,3049.0,NaN,0.070,30.0,102.0,NaN,0.0,NaN,0.0,NaN,300.0,300.0,300.0,300.0,West End,00003,VACANT RESIDENTIAL,4.0
6,21042799.,DETROIT,"MALLARD, SCOTT",402.0,RESIDENTIAL-VACANT,TAXABLE,3311.0,NaN,0.076,32.0,103.0,NaN,0.0,NaN,49500.0,8/21/2007 12:00:00 AM,0.0,0.0,0.0,0.0,West End,00003,VACANT RESIDENTIAL,4.0
7,21047341.,DETROIT,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,14000.0,7/1/1971 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,00VAC,NaN,4.0
8,21047551.,DETROIT,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4792.0,NaN,0.110,40.0,120.0,NaN,0.0,NaN,7300.0,10/1/1981 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,00VAC,NaN,4.0
9,21047578.,DETROIT,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4270.0,NaN,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Riverbend,00VAC,NaN,4.0

In [30]:
parcels2["Taxpayer City"] = np.where(parcels2["Taxpayer City"] == "DETROIT", 1, 0)

<ipython-input-30-ad77c6b306d4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  parcels2["Taxpayer City"] = np.where(parcels2["Taxpayer City"] == "DETROIT", 1, 0)

In [31]:
parcels2.head(10)

,Parcel ID,Taxpayer City,Taxpayer 1,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Floor Area,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Council District
0,21019476.,1,"BOOKER, TRANYSSA",402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,NaN,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,3.0
1,21019749.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,NaN,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0
2,21019245.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,NaN,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0
3,21019205.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,NaN,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0
4,21048771.,1,1 MONTCLAIR LLC,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,NaN,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,4.0
5,21042930-1,1,"BAILEY, ABAYOMI",402.0,RESIDENTIAL-VACANT,TAXABLE,3049.0,NaN,0.070,30.0,102.0,NaN,0.0,NaN,0.0,NaN,300.0,300.0,300.0,300.0,West End,00003,VACANT RESIDENTIAL,4.0
6,21042799.,1,"MALLARD, SCOTT",402.0,RESIDENTIAL-VACANT,TAXABLE,3311.0,NaN,0.076,32.0,103.0,NaN,0.0,NaN,49500.0,8/21/2007 12:00:00 AM,0.0,0.0,0.0,0.0,West End,00003,VACANT RESIDENTIAL,4.0
7,21047341.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,14000.0,7/1/1971 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,00VAC,NaN,4.0
8,21047551.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4792.0,NaN,0.110,40.0,120.0,NaN,0.0,NaN,7300.0,10/1/1981 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,00VAC,NaN,4.0
9,21047578.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4270.0,NaN,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Riverbend,00VAC,NaN,4.0

### POLICE DATA

In [32]:
police =pd.read_csv('/content/drive/MyDrive/detroit data/Police_Serviced_911_Calls_805604165310935371.csv')
police1 = police.loc[:,['Code Description','Category','Priority','Call Time','Neighborhood Name','Council District']]

In [33]:
group1 = ['P', '1','2','3']
def p1(Priority):
  if Priority in group1:
    return 1
  else:
    return 0
police1['High_Priority'] = police1['Priority'].apply(p1)
police1.head()

,Code Description,Category,Priority,Call Time,Neighborhood Name,Council District,High_Priority
0,INVESTIGATE AUTO,INVAUTO,5,8/7/2024 2:01:09 PM,Franklin,3.0,0
1,VERIFIED ALR / PERSON W/O CODE,VERALRM,2,8/7/2024 1:49:28 PM,Historic Atkinson,5.0,1
2,UNKNOWN PROBLEM,UNKPROB,2,8/7/2024 1:49:26 PM,Krainz Woods,3.0,1
3,UNKNOWN PROBLEM,UNKPROB,2,8/7/2024 1:43:08 PM,New Center Commons,5.0,1
4,WELL BEING CHECK,WBC,3,8/7/2024 1:37:50 PM,Central Southwest,6.0,1

In [34]:
police1[['Month','Day', 'temp']] = police1['Call Time'].str.split('/',expand=True)
police1=police1.drop(columns=['Call Time','Month','Day'])
def getYear(y):
 if y:
  return y[0:4]

police1['Year'] = police1['temp'].apply(getYear)
police1.head()

,Code Description,Category,Priority,Neighborhood Name,Council District,High_Priority,temp,Year
0,INVESTIGATE AUTO,INVAUTO,5,Franklin,3.0,0,2024 2:01:09 PM,2024
1,VERIFIED ALR / PERSON W/O CODE,VERALRM,2,Historic Atkinson,5.0,1,2024 1:49:28 PM,2024
2,UNKNOWN PROBLEM,UNKPROB,2,Krainz Woods,3.0,1,2024 1:49:26 PM,2024
3,UNKNOWN PROBLEM,UNKPROB,2,New Center Commons,5.0,1,2024 1:43:08 PM,2024
4,WELL BEING CHECK,WBC,3,Central Southwest,6.0,1,2024 1:37:50 PM,2024

In [35]:
police1 = police1.loc[police1['Year'].isin(['2019', '2020', '2021', '2022', '2023'])]
policd1 = police1.loc[police1['High_Priority'] == 1]
police1 = police1.drop(columns=['temp','Code Description','Category','Priority','Council District'])
police1.head()

        Neighborhood Name  High_Priority  Year
194056     Dexter-Linwood              1  2023
194057            Midwest              1  2023
194058  Central Southwest              1  2023
194059  Bethune Community              1  2023
194060       Elmwood Park              1  2023

In [36]:
count_df = police1.groupby(['Year', 'Neighborhood Name']).size().reset_index(name='count')
finalpolice_df = count_df.groupby('Neighborhood Name')['count'].mean().reset_index(name='yearly_average')
#gives yearly high priority serviced calls by neighborhood
finalpolice_df.head()

  Neighborhood Name  yearly_average
0       Airport Sub          3553.2
1        Arden Park            62.6
2      Aviation Sub           818.6
3            Bagley          3233.4
4  Barton-McFarland          4377.8

### MERGING DATASETS

parcels2

In [37]:
blight = blight_violations_1
policedf = finalpolice_df
#parcels2
bpermits = building_permits_1

In [38]:
blight1 = blight.loc[blight['violation_date'] >= '2019-01-01']

In [39]:
blight1.head()

         parcelno violation_date  fine_amount
374225  22086750.     2019-03-23        200.0
391218  21077857.     2020-10-01        500.0
391220  21077857.     2020-10-01        250.0
394859  21062691.     2020-10-30        250.0
402000  22121565.     2019-01-02        250.0

In [40]:
blight2 = blight1.loc[blight1.groupby('parcelno')['violation_date'].idxmax()]
blight2.head()

             parcelno violation_date  fine_amount
462442      01000001.     2020-01-23        250.0
459231  01000004.002L     2020-01-08        250.0
594863   01000007.001     2022-04-13        250.0
460535      01000087.     2020-01-09        250.0
645649   01000088-109     2023-03-29        250.0

In [41]:
permtemp = bpermits
permtemp['Date Issued'] = pd.to_datetime(permtemp['Date Issued'])
bpermits1 = permtemp
bpermits1.head(2)

<ipython-input-41-a9426a4f9649>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  permtemp['Date Issued'] = pd.to_datetime(permtemp['Date Issued'])
<ipython-input-41-a9426a4f9649>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  permtemp['Date Issued'] = pd.to_datetime(permtemp['Date Issued'])

   Parcel ID Date Issued Permit Status
0  22107015.  2020-07-27        Issued
1  22104480.  2020-07-20        Issued

In [42]:
bpermits2 = bpermits1.loc[bpermits1.groupby('Parcel ID')['Date Issued'].idxmax()]
bpermits2.head()

      Parcel ID Date Issued Permit Status
3748       -501  2019-02-21        Issued
7250       -502  2019-10-24        Issued
29214      -504  2024-05-07        Issued
26507      -506  2024-01-10        Issued
1506       -507  2019-01-31        Issued

In [43]:
blight2.head()

             parcelno violation_date  fine_amount
462442      01000001.     2020-01-23        250.0
459231  01000004.002L     2020-01-08        250.0
594863   01000007.001     2022-04-13        250.0
460535      01000087.     2020-01-09        250.0
645649   01000088-109     2023-03-29        250.0

In [44]:
blight2 = blight2.rename(columns={})

In [45]:
try1 = pd.merge(parcels2, bpermits2, how='left', on='Parcel ID')
try1fix = try1.dropna(subset='Parcel ID')
try1fix.head(5)

,Parcel ID,Taxpayer City,Taxpayer 1,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Floor Area,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Council District,Date Issued,Permit Status
0,21019476.,1,"BOOKER, TRANYSSA",402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,NaN,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,3.0,NaT,NaN
1,21019749.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,NaN,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN
2,21019245.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,NaN,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN
3,21019205.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,NaN,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN
4,21048771.,1,1 MONTCLAIR LLC,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,NaN,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN

In [46]:
try2 = pd.merge(try1fix, blight2, how="left", left_on='Parcel ID', right_on='parcelno')
try2fix = try2.dropna(subset='Parcel ID')
try2fix.head(200)

,Parcel ID,Taxpayer City,Taxpayer 1,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Floor Area,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Council District,Date Issued,Permit Status,parcelno,violation_date,fine_amount
0,21019476.,1,"BOOKER, TRANYSSA",402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,NaN,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
1,21019749.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,NaN,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
2,21019245.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,NaN,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
3,21019205.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,NaN,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
4,21048771.,1,1 MONTCLAIR LLC,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,NaN,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,21048771.,2019-03-13,250.0
5,21042930-1,1,"BAILEY, ABAYOMI",402.0,RESIDENTIAL-VACANT,TAXABLE,3049.0,NaN,0.070,30.0,102.0,NaN,0.0,NaN,0.0,NaN,300.0,300.0,300.0,300.0,West End,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
6,21042799.,1,"MALLARD, SCOTT",402.0,RESIDENTIAL-VACANT,TAXABLE,3311.0,NaN,0.076,32.0,103.0,NaN,0.0,NaN,49500.0,8/21/2007 12:00:00 AM,0.0,0.0,0.0,0.0,West End,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
7,21047341.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,14000.0,7/1/1971 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
8,21047551.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4792.0,NaN,0.110,40.0,120.0,NaN,0.0,NaN,7300.0,10/1/1981 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
9,21047578.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4270.0,NaN,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Riverbend,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
10,21047831.,1,"DONWELL, WILLIE",402.0,RESIDENTIAL-VACANT,TAXABLE,4283.0,NaN,0.098,35.0,122.0,NaN,0.0,NaN,0.0,NaN,800.0,800.0,243.0,232.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
11,21048345.,0,DICKERSON MANOR/MHT LDHA LP,402.0,RESIDENTIAL-VACANT,EXEMPT (125.1415A),4008.0,NaN,0.092,40.0,100.0,NaN,0.0,NaN,2691.0,7/26/2004 12:00:00 AM,0.0,0.0,0.0,0.0,Jefferson Chalmers,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
12,21048148.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3013.0,NaN,0.069,30.0,100.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Jefferson Chalmers,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
13,21050070.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3210.0,NaN,0.074,30.0,107.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Riverbend,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
14,21050056.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3180.0,NaN,0.073,30.0,106.0,NaN,0.0,NaN,632.0,11/1/1995 12:00:00 AM,0.0,0.0,0.0,0.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
15,21049906.,1,"THORNTON, RODNEY & YOLANDA",402.0,RESIDENTIAL-VACANT,TAXABLE,3500.0,NaN,0.080,35.0,100.0,NaN,0.0,NaN,500.0,10/10/2007 12:00:00 AM,300.0,300.0,232.0,221.0,Chandler Park,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
16,21033718.,1,"BROOKS, ORLANDO",402.0,RESIDENTIAL-VACANT,TAXABLE,3850.0,NaN,0.088,35.0,110.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Von Steuben,00VAC,NaN,3.0,NaT,NaN,NaN,NaT,NaN
17,21048812.002L,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Riverbend,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
18,21048804.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3660.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,13000.0,7/1/1970 12:00:00 AM,0.0,0.0,0.0,0.0,Riverbend,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
19,21048953.,1,"FARR, ELARY",402.0,RESIDENTIAL-VACANT,TAXABLE,3615.0,NaN,0.083,30.0,121.0,NaN,0.0,NaN,7600.0,5/1/1968 12:00:00 AM,500.0,500.0,119.0,114.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
20,21076071.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6882.0,NaN,0.158,60.0,114.0,NaN,0.0,NaN,7500.0,8/11/2008 12:00:00 AM,0.0,0.0,0.0,0.0,Cornerstone Village,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
21,21074089.,1,"GUYTON, JOYCE",402.0,RESIDENTIAL-VACANT,TAXABLE,4428.0,NaN,0.102,39.0,114.0,NaN,0.0,NaN,105000.0,8/24/2006 12:00:00 AM,500.0,500.0,500.0,500.0,Denby,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,21074089.,2021-11-02,500.0
22,21080882.,0,"WILLIAMS, ADAMSKIE",402.0,RESIDENTIAL-VACANT,TAXABLE,5619.0,NaN,0.129,47.0,120.0,Outer Drive - Gratiot (H057),0.0,NaN,5600.0,10/16/2017 12:00:00 AM,500.0,500.0,500.0,500.0,Wade,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,21080882.,2019-08-13,125.0
23,21080731.,1,"MCIVER, LAWRENCE",402.0,RESIDENTIAL-VACANT,TAXABLE,6011.0,NaN,0.138,50.0,120.0,Outer Drive - Gratiot (H057),0.0,NaN,9000.0,8/21/2017 12:00:00 AM,500.0,500.0,500.0,500.0,Eden Gardens,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
24,21080796.,1,"TRIPP, FRDERICK",402.0,RESIDENTIAL-VACANT,TAXABLE,5657.0,NaN,0.130,47.0,120.0,Outer Drive - Gratiot (H057),0.0,NaN,98421.0,10/24/2003 12:00:00 AM,500.0,500.0,500.0,500.0,Eden Gardens,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,21080796.,2024-06-26,125.0
25,21065437.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3659.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,6300.0,5/23/2003 12:00:00 AM,0.0,0.0,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
26,21065434.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3668.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,9885.0,10/1/1981 12:00:00 AM,0.0,0.0,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
27,21064654.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3659.0,NaN,0.084,30.0,122.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
28,21068129.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5389.0,NaN,0.124,45.0,120.0,NaN,0.0,NaN,40900.0,8/1/1996 12:00:00 AM,0.0,0.0,0.0,0.0,Yorkshire Woods,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
29,21064577.,1,"LEWIS, LAUREEN",402.0,RESIDENTIAL-VACANT,TAXABLE,3441.0,NaN,0.079,30.0,115.0,Warren - Alter Rd (H060),0.0,NaN,1000.0,7/4/2002 12:00:00 AM,300.0,300.0,300.0,300.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
30,21064553.,1,"FERRARO, JAMES",402.0,RESIDENTIAL-VACANT,TAXABLE,3441.0,NaN,0.079,30.0,115.0,Warren - Alter Rd (H060),0.0,NaN,0.0,NaN,300.0,300.0,300.0,232.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
31,21064350.,1,"TURNER, LATRICE",402.0,RESIDENTIAL-VACANT,TAXABLE,4008.0,NaN,0.092,35.0,114.0,NaN,0.0,NaN,44000.0,8/1/1998 12:00:00 AM,0.0,0.0,0.0,0.0,Morningside,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
32,21064333.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4008.0,NaN,0.092,35.0,114.0,NaN,0.0,NaN,9000.0,4/1/1982 12:00:00 AM,0.0,0.0,0.0,0.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
33,21064409.,1,"LAWSON, ERICA",402.0,RESIDENTIAL-VACANT,TAXABLE,3964.0,NaN,0.091,35.0,114.0,Warren - Alter Rd (H060),0.0,NaN,2500.0,9/26/2008 12:00:00 AM,400.0,400.0,400.0,400.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
34,21063089.,1,CHALMERS HEIGHTS DEVELOPMENT LLC,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7M),3510.0,NaN,0.081,30.0,117.0,NaN,0.0,NaN,7300.0,7/13/2007 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
35,21062884.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3511.0,NaN,0.081,35.0,101.0,Warren - Alter Rd (H060),0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Morningside,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
36,21063051.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3131.0,NaN,0.072,30.0,104.0,NaN,0.0,NaN,11020.0,3/1/1974 12:00:00 AM,0.0,0.0,0.0,0.0,Fox Creek,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN
37,21062560.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3453.0,NaN,0.079,30.0,115.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Jefferson Chalmers,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
38,21062364.,1,"WALINSKE, LISA",402.0,RESIDENTIAL-VACANT,TAXABLE,3000.0,NaN,0.069,30.0,100.0,NaN,0.0,NaN,12900.0,12/1/1974 12:00:00 AM,300.0,300.0,300.0,300.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
39,21062398.,1,NEW FAR EAST SIDE DEVELOPMENT CO,402.0,RESIDENTIAL-VACANT,TAXABLE,3006.0,NaN,0.069,30.0,100.0,NaN,0.0,NaN,11000.0,5/1/1980 12:00:00 AM,300.0,300.0,300.0,300.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
40,21010242.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4254.0,NaN,0.098,40.0,106.0,NaN,0.0,NaN,2350.0,8/1/1988 12:00:00 AM,0.0,0.0,0.0,0.0,Outer Drive-Hayes,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
41,21014737.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3833.0,NaN,0.088,35.0,110.0,NaN,0.0,NaN,11337.0,5/1/1989 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
42,21017765.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4112.0,NaN,0.094,40.0,112.0,NaN,0.0,NaN,20500.0,10/1/1981 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
43,21017614.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3615.0,NaN,0.083,35.0,103.0,NaN,0.0,NaN,16457.0,3/1/1980 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
44,21017872.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3703.0,NaN,0.085,36.0,103.0,NaN,0.0,NaN,4000.0,8/1/1996 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
45,21017893.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4138.0,NaN,0.095,40.0,103.0,NaN,0.0,NaN,900.0,2/22/2008 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,41310,INCOME BUNGALOW,4.0,NaT,NaN,NaN,NaT,NaN
46,21018087.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3441.0,NaN,0.079,33.0,103.0,NaN,0.0,NaN,9000.0,8/30/2004 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
47,21018086.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3441.0,NaN,0.079,33.0,103.0,NaN,0.0,NaN,8000.0,9/1/1993 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
48,21018132.,1,"AKINS, ZELMA",402.0,RESIDENTIAL-VACANT,TAXABLE,3703.0,NaN,0.085,36.0,103.0,NaN,0.0,NaN,6500.0,12/1/1988 12:00:00 AM,200.0,200.0,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
49,21013047.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3790.0,NaN,0.087,35.0,109.0,NaN,0.0,NaN,14900.0,10/1/1987 12:00:00 AM,0.0,0.0,0.0,0.0,Gratiot-Findlay,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
50,21013433.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4231.0,NaN,0.097,35.0,121.0,NaN,0.0,NaN,6350.0,1/1/1993 12:00:00 AM,0.0,0.0,0.0,0.0,LaSalle College Park,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
51,21014512.,1,"CLARK-CARLISLE, CLARENCETTA M",402.0,RESIDENTIAL-VACANT,TAXABLE,3441.0,NaN,0.079,30.0,114.0,NaN,0.0,NaN,500.0,7/17/2008 12:00:00 AM,200.0,200.0,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
52,21014673.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3877.0,NaN,0.089,35.0,111.0,NaN,0.0,NaN,2000.0,4/1/1987 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
53,21015869.,1,"WESSON, REGINALD",402.0,RESIDENTIAL-VACANT,TAXABLE,3833.0,NaN,0.088,35.0,110.0,NaN,0.0,NaN,12500.0,11/8/2004 12:00:00 AM,200.0,200.0,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
54,21014829.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3920.0,NaN,0.090,35.0,112.0,NaN,0.0,NaN,22500.0,1/1/1982 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
55,21014948.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4291.0,NaN,0.099,38.0,112.0,NaN,0.0,NaN,501.0,9/3/2005 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
56,21014871.,1,"PITTS, FLOYD",402.0,RESIDENTIAL-VACANT,TAXABLE,3920.0,NaN,0.090,35.0,112.0,NaN,0.0,NaN,1600.0,9/20/2010 12:00:00 AM,200.0,200.0,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,21014871.,2022-07-09,500.0
57,21015261.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3360.0,NaN,0.077,30.0,112.0,NaN,0.0,NaN,14500.0,7/1/1969 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
58,21015228.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3354.0,NaN,0.077,30.0,112.0,NaN,0.0,NaN,8500.0,6/1/1985 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
59,21015320.,1,"EDWARDS, NORMA",402.0,RESIDENTIAL-VACANT,TAXABLE,3354.0,NaN,0.077,30.0,112.0,NaN,0.0,NaN,0.0,NaN,200.0,200.0,200.0,200.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
60,21035950.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5401.0,NaN,0.124,40.0,135.0,NaN,0.0,NaN,48814.0,7/5/2011 12:00:00 AM,0.0,0.0,0.0,0.0,Pulaski,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
61,21035446.,1,"COSTNER, SHATISHA",402.0,RESIDENTIAL-VACANT,TAXABLE,4400.0,NaN,0.101,35.0,126.0,NaN,0.0,NaN,26000.0,11/1/1978 12:00:00 AM,400.0,400.0,400.0,400.0,Pulaski,00VAC,NaN,3.0,NaT,NaN,NaN,NaT,NaN
62,21034775.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5097.0,NaN,0.117,40.0,127.0,NaN,0.0,NaN,5000.0,6/10/2009 12:00:00 AM,0.0,0.0,0.0,0.0,Conner Creek,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
63,21034654.,1,"PEARCE TATE, LORANE",402.0,RESIDENTIAL-VACANT,TAXABLE,4746.0,NaN,0.109,35.0,136.0,NaN,0.0,NaN,95000.0,10/17/2005 12:00:00 AM,400.0,400.0,400.0,400.0,Von Steuben,00VAC,NaN,3.0,NaT,NaN,21034654.,2023-08-24,50.0
64,21033679.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4051.0,NaN,0.093,40.0,101.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,LaSalle College Park,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
65,21018640.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6173.0,NaN,0.142,60.0,103.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
66,21010270-2,1,DETROIT PARKS & RECREATION,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7M),29648.0,NaN,0.681,218.0,136.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Outer Drive-Hayes,00001,IMPROVED NO BLDG,4.0,NaT,NaN,NaN,NaT,NaN
67,21010384.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4008.0,NaN,0.092,35.0,115.0,NaN,0.0,NaN,3000.0,7/13/2007 12:00:00 AM,0.0,0.0,0.0,0.0,Outer Drive-Hayes,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
68,21010404.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,NaN,0.099,40.0,107.0,NaN,0.0,NaN,29500.0,7/26/2005 12:00:00 AM,0.0,0.0,0.0,0.0,Outer Drive-Hayes,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN
69,21009020.,1,"SWAIN, NATHANIEL AND JACQUELINE",402.0,RESIDENTIAL-VACANT,EXEMPT (211.7M),4200.0,NaN,0.096,40.0,105.0,NaN,0.0,NaN,19500.0,4/1/1979 12:00:00 AM,0.0,0.0,0.0,0.0,Wade,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
70,21009030.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3659.0,NaN,0.084,35.0,105.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Wade,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
71,21009072.,1,"MCLAUGHLIN WOODS, LULA",402.0,RESIDENTIAL-VACANT,TAXABLE,3674.0,NaN,0.084,35.0,105.0,NaN,0.0,NaN,21000.0,1/1/1993 12:00:00 AM,200.0,200.0,200.0,200.0,Wade,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
72,21020355.,1,"MARTINEZ, WILSON",402.0,RESIDENTIAL-VACANT,TAXABLE,4356.0,NaN,0.100,38.0,115.0,NaN,0.0,NaN,52324.0,10/11/2007 12:00:00 AM,0.0,0.0,0.0,0.0,Von Steuben,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
73,21019065.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4138.0,NaN,0.095,40.0,103.0,NaN,0.0,NaN,4767.0,5/1/1989 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
74,21018431.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4017.0,NaN,0.092,39.0,103.0,NaN,0.0,NaN,11500.0,8/1/1978 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
75,21018455.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3703.0,NaN,0.085,36.0,103.0,NaN,0.0,NaN,4000.0,11/1/1978 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
76,21018465.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),6874.0,NaN,0.158,42.0,164.0,NaN,0.0,NaN,7500.0,2/23/2006 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
77,21019445.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3708.0,NaN,0.085,36.0,103.0,NaN,0.0,NaN,2500.0,3/1/1995 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
78,21023505.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5271.0,NaN,0.121,42.0,125.0,NaN,0.0,NaN,30000.0,10/1/2012 12:00:00 AM,0.0,0.0,0.0,0.0,Regent Park,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
79,21022766.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3136.0,NaN,0.072,30.0,104.0,NaN,0.0,NaN,35000.0,8/9/2005 12:00:00 AM,200.0,200.0,200.0,200.0,Regent Park,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
80,21022404.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4138.0,NaN,0.095,40.0,104.0,NaN,0.0,NaN,48000.0,11/9/2007 12:00:00 AM,0.0,0.0,0.0,0.0,Regent Park,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
81,21022566.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),5401.0,NaN,0.124,40.0,135.0,NaN,0.0,NaN,89000.0,10/10/2006 12:00:00 AM,0.0,0.0,0.0,0.0,Regent Park,00VAC,NaN,3.0,NaT,NaN,NaN,NaT,NaN
82,21021965.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4025.0,NaN,0.092,35.0,115.0,NaN,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,Franklin,00VAC,NaN,3.0,NaT,NaN,NaN,NaT,NaN
83,21016503.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4713.0,NaN,0.108,40.0,118.0,NaN,0.0,NaN,5500.0,2/1/1975 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
84,21016385.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3833.0,NaN,0.088,35.0,110.0,NaN,0.0,NaN,2500.0,3/1/1987 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
85,21016345.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3850.0,NaN,0.088,35.0,110.0,NaN,0.0,NaN,16523.0,3/1/1983 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN
86,21015573.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3354.0,NaN,0.077,30.0,112.0,NaN,0.0,NaN,3500.0,12/1/1988 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN
87,21015606.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4530.0,NaN,0.104,36.0,126.0,NaN,0.0,NaN,48000.0,9/1/2001 12:00:00 AM,0.0,0.0,0.0,0.0,Franklin,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN
88,21066462.,0,HUD,402.0,RESIDENTIAL-VACANT,TAXABLE,5140.0,NaN,0.118,40.0,128.0,NaN,0.0,NaN,89307.0,10/15/2009 12:00:00 AM,600.0,600.0,600.0,586.0,Morningside,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,NaN,NaT,NaN

In [47]:
try3 = pd.merge(try2fix, policedf, how='left', left_on = 'Neighborhood', right_on='Neighborhood Name')

In [48]:
try3.head()

,Parcel ID,Taxpayer City,Taxpayer 1,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Floor Area,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Council District,Date Issued,Permit Status,parcelno,violation_date,fine_amount,Neighborhood Name,yearly_average
0,21019476.,1,"BOOKER, TRANYSSA",402.0,RESIDENTIAL-VACANT,TAXABLE,4617.0,NaN,0.106,35.0,131.0,NaN,0.0,NaN,0.0,NaN,400.0,400.0,400.0,400.0,Franklin,00003,VACANT RESIDENTIAL,3.0,NaT,NaN,NaN,NaT,NaN,Franklin,1849.6
1,21019749.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),4312.0,NaN,0.099,42.0,103.0,NaN,0.0,NaN,915.0,10/19/2012 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN,Mapleridge,3387.6
2,21019245.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3605.0,NaN,0.083,35.0,103.0,NaN,0.0,NaN,18000.0,8/1/1991 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN,Mapleridge,3387.6
3,21019205.,1,DETROIT LAND BANK AUTHORITY,402.0,RESIDENTIAL-VACANT,EXEMPT (211.7GG),3399.0,NaN,0.078,33.0,103.0,NaN,0.0,NaN,13168.0,4/1/1982 12:00:00 AM,0.0,0.0,0.0,0.0,Mapleridge,00VAC,NaN,4.0,NaT,NaN,NaN,NaT,NaN,Mapleridge,3387.6
4,21048771.,1,1 MONTCLAIR LLC,402.0,RESIDENTIAL-VACANT,TAXABLE,3746.0,NaN,0.086,31.0,121.0,NaN,0.0,NaN,2620.0,4/1/2000 12:00:00 AM,600.0,600.0,600.0,600.0,Riverbend,00003,VACANT RESIDENTIAL,4.0,NaT,NaN,21048771.,2019-03-13,250.0,Riverbend,1610.6

In [49]:
try3["Year Built"].unique()

array([  nan, 1916., 2002., 1938., 1929., 1937., 1941., 1927., 1939.,
       1942., 1944., 1947., 1945., 1940., 1930., 1936., 1943., 1928.,
       1953., 1926., 1948., 1925., 1952., 1951., 1955., 1924., 2000.,
       2014., 1950., 1996., 1918., 1931., 1919., 1923., 1935., 1920.,
       1915., 1946., 1959., 1922., 1921., 1957., 1954., 1960., 1917.,
       1992., 1963., 1949., 1932., 1964., 1956., 1961., 1912., 1962.,
       1999., 2015., 1934., 2006., 2007., 1914., 1958., 1971., 1933.,
       1998., 1968., 1911., 1913., 1910., 2004., 1966., 1970., 1994.,
       1973., 2003., 1995., 1965., 2001., 2010., 1993., 1967., 2013.,
       1981., 2022., 1972., 1908., 2011., 1895., 2009., 1907., 2005.,
       1980., 2017., 1900., 1969., 1979., 1983., 1905., 1909., 1906.,
       1890., 1902., 1904., 1897., 1903., 1880., 1885., 1898., 1891.,
       1987., 1901., 2008., 1868., 1894., 1888., 1899., 1850., 1988.,
       1990., 1869., 1875., 2012., 1977., 1984., 1985., 1975., 1884.,
       1882., 1887., 2020., 1892., 1997., 1870., 1872., 1978., 1825.,
       2107., 2018., 2019., 1840., 1893., 1886., 1896., 1974., 1889.,
       2023., 1879., 1976., 1989., 1986., 1865., 1881., 1877., 1874.,
       1860., 1982., 1853., 1876., 1991., 1883., 2016., 1829., 1878.,
       1822., 2021.])

In [50]:
value_counts = try3["Property Class Description"].value_counts()
value_percentages = value_counts / len(try3) * 100
value_percentages

Property Class Description
RESIDENTIAL-IMPROVED    65.183015
RESIDENTIAL-VACANT      34.816985
Name: count, dtype: float64

In [51]:
#slimming down to residential_improved data (meaning it has a property on the lot)
residential_improved_count =(try3["Property Class Description"]=='RESIDENTIAL-IMPROVED').sum()
residential_improved_count

218221

In [52]:
#drop land without a resedencial structure on it
try3 = try3.drop(try3[(try3['Building Count'] == 0) & (try3['Property Class Description'] == 'RESIDENTIAL-VACANT')].index)
try3 = try3.drop(try3[(try3['Building Count'] == 0) & (try3['Property Class Description'] == 'RESIDENTIAL-IMPROVED')].index)
len(try3)

211975

In [53]:
#residential improved sttuctures count with a vacant residential sturuture on it
residential_improved_count =(try3["Property Class Description"]=='RESIDENTIAL-VACANT').sum()
residential_improved_count

57

In [54]:
try3.head()

,Parcel ID,Taxpayer City,Taxpayer 1,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Floor Area,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Council District,Date Issued,Permit Status,parcelno,violation_date,fine_amount,Neighborhood Name,yearly_average
239,21062470.,1,853 ASHLAND LLC,401.0,RESIDENTIAL-IMPROVED,TAXABLE,3441.0,2468.0,0.079,30.0,115.0,NaN,1.0,1916.0,65000.0,9/14/2021 12:00:00 AM,46200.0,61300.0,61300.0,16361.0,Jefferson Chalmers,41210,TWO FAMILY,4.0,NaT,NaN,21062470.,2024-04-16,250.0,Jefferson Chalmers,1602.2
266,21063979.,0,"CASTLE, ROBERT M",401.0,RESIDENTIAL-IMPROVED,TAXABLE,0.0,1389.0,0.000,0.0,0.0,Warren - Alter Rd (H060),1.0,2002.0,13600.0,2/14/2014 12:00:00 AM,31700.0,40100.0,13286.0,12654.0,Morningside,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0
277,21068429.,0,CITIMORTGAGE INC,401.0,RESIDENTIAL-IMPROVED,TAXABLE,5009.0,1293.0,0.115,40.0,126.0,NaN,1.0,1938.0,79992.0,7/27/2023 12:00:00 AM,33400.0,40400.0,40400.0,15835.0,Moross-Morang,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Moross-Morang,3200.6
278,21069819.,1,"ROBINSON, DENISE",401.0,RESIDENTIAL-IMPROVED,TAXABLE,4574.0,1540.0,0.105,40.0,114.0,NaN,1.0,1929.0,8912.0,4/30/2010 12:00:00 AM,31300.0,39900.0,14391.0,13706.0,Morningside,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0
279,21070146.,1,"BRADFORD, WILLIAM",401.0,RESIDENTIAL-IMPROVED,TAXABLE,4661.0,920.0,0.107,40.0,116.0,NaN,1.0,1938.0,20000.0,9/1/1987 12:00:00 AM,16200.0,20300.0,9396.0,8949.0,Outer Drive-Hayes,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Outer Drive-Hayes,4247.8

In [55]:
#importing in vacancy data
vacancy = pd.read_csv('/content/drive/MyDrive/detroit data/Vacant_Property_Registrations.csv')
vacancy = vacancy.rename(columns={"parcel_id": "Parcel ID"})
vacancy.head(10)
#parcelno

,X,Y,record_id,street_num,street_dir,street_name,date_status,address_id,Parcel ID,lon,lat,ObjectId
0,-9.254395e+06,5.217372e+06,VPO2010-03803,11626,NaN,YELLOWSTONE,2024/04/01 04:00:00+00,74606.0,14012633.,-83.133645,42.375352,1
1,-9.251294e+06,5.223992e+06,VPO2011-00161,17428,NaN,WOODWARD,2024/03/21 04:00:00+00,538386.0,01009693.,-83.105790,42.419267,2
2,-9.230812e+06,5.221026e+06,VPO2011-02997,3940,NaN,GUILFORD,2024/04/11 04:00:00+00,317717.0,21075610.,-82.921793,42.399594,3
3,-9.249232e+06,5.218158e+06,VPO2011-03556,751,NaN,CLAIRMOUNT,2022/05/04 04:00:00+00,344110.0,04002447.,-83.087269,42.380564,4
4,-9.263078e+06,5.227642e+06,VPO2011-05004,20543,NaN,FERGUSON,2023/04/05 04:00:00+00,73135.0,22063524.,-83.211644,42.443471,5
5,-9.264072e+06,5.212703e+06,VPO2011-05239,7264,NaN,FAUST,2023/09/21 04:00:00+00,161210.0,22078398.,-83.220578,42.344355,6
6,-9.250129e+06,5.208867e+06,VPO2011-06080,1601,NaN,CLARK,2023/12/19 05:00:00+00,178373.0,14010191.,-83.095327,42.318885,7
7,-9.251402e+06,5.218617e+06,VPO2011-06245,2005,NaN,LAWRENCE,2024/02/12 05:00:00+00,51115.0,08003328.,-83.106757,42.383611,8
8,-9.268162e+06,5.223484e+06,VPO2011-07779,17224,NaN,LAHSER,2023/09/13 04:00:00+00,390727.0,22113377.,-83.257316,42.415897,9
9,-9.249891e+06,5.216829e+06,VPO2011-09852,1612,W,EUCLID,2023/12/15 05:00:00+00,535612.0,08002127.,-83.093189,42.371747,10

In [56]:
#matched houses claimed to be residential imporved but are actually vacant according to the vacant dataset
column_name = 'Parcel ID'
matches = pd.Series(try3[column_name]).isin(vacancy[column_name])
count_matches = matches.sum()

print(f"Number of matching rows: {count_matches}")

Number of matching rows: 2591

In [57]:
#creating the vacant row in the main datset based on matches in previous cell
column_name = 'Parcel ID'
try3['vacant'] = try3[column_name].isin(vacancy[column_name]).astype(int)
try3.head()

,Parcel ID,Taxpayer City,Taxpayer 1,Property Class,Property Class Description,Tax Status,Total Square Footage,Total Floor Area,Total Acreage,Frontage,Depth,NEZ District,Building Count,Year Built,Sale Price,Sale Date,Previous Assessed Value,Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Use Code,Use Code Description,Council District,Date Issued,Permit Status,parcelno,violation_date,fine_amount,Neighborhood Name,yearly_average,vacant
239,21062470.,1,853 ASHLAND LLC,401.0,RESIDENTIAL-IMPROVED,TAXABLE,3441.0,2468.0,0.079,30.0,115.0,NaN,1.0,1916.0,65000.0,9/14/2021 12:00:00 AM,46200.0,61300.0,61300.0,16361.0,Jefferson Chalmers,41210,TWO FAMILY,4.0,NaT,NaN,21062470.,2024-04-16,250.0,Jefferson Chalmers,1602.2,0
266,21063979.,0,"CASTLE, ROBERT M",401.0,RESIDENTIAL-IMPROVED,TAXABLE,0.0,1389.0,0.000,0.0,0.0,Warren - Alter Rd (H060),1.0,2002.0,13600.0,2/14/2014 12:00:00 AM,31700.0,40100.0,13286.0,12654.0,Morningside,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0,0
277,21068429.,0,CITIMORTGAGE INC,401.0,RESIDENTIAL-IMPROVED,TAXABLE,5009.0,1293.0,0.115,40.0,126.0,NaN,1.0,1938.0,79992.0,7/27/2023 12:00:00 AM,33400.0,40400.0,40400.0,15835.0,Moross-Morang,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Moross-Morang,3200.6,0
278,21069819.,1,"ROBINSON, DENISE",401.0,RESIDENTIAL-IMPROVED,TAXABLE,4574.0,1540.0,0.105,40.0,114.0,NaN,1.0,1929.0,8912.0,4/30/2010 12:00:00 AM,31300.0,39900.0,14391.0,13706.0,Morningside,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Morningside,3541.0,0
279,21070146.,1,"BRADFORD, WILLIAM",401.0,RESIDENTIAL-IMPROVED,TAXABLE,4661.0,920.0,0.107,40.0,116.0,NaN,1.0,1938.0,20000.0,9/1/1987 12:00:00 AM,16200.0,20300.0,9396.0,8949.0,Outer Drive-Hayes,41110,SINGLE FAMILY,4.0,NaT,NaN,NaN,NaT,NaN,Outer Drive-Hayes,4247.8,0

In [58]:
#propety with vacant house in the main dataset
#not sure why its 7 less than expected from the matches but close need to check this
vacancy_house = ((try3["Building Count"] == 1) & (try3['vacant'] == 1)).sum()
print(vacancy_house)

2584

In [59]:
#checking the sum of if taxpayer is land bank authority and there is a building the property (also needs to be labeled vacant)
land_bank_vacant = ((try3["Taxpayer 1"] == "DETROIT LAND BANK AUTHORITY") & (try3['Building Count'] == 1)).sum()
land_bank_vacant

10232

In [60]:
(2584 + 10232)

12816

In [61]:
#if taxpayer is land bank authority and there is a building, label the property as vacant
try3.loc[((try3["Taxpayer 1"] == "DETROIT LAND BANK AUTHORITY") & (try3['Building Count'] == 1)), 'vacant'] = 1
sum(try3['vacant'] == 1)

12809

In [83]:
clean = try3[["Parcel ID",
                    "Taxpayer 1",
                    "Taxpayer City",
                    "Property Class",
                    "Tax Status",
                    "Total Floor Area",
                    "Total Acreage",
                    "Frontage",
                    "Depth",
                    "Building Count",
                    "Year Built",
                    "Sale Price",
                    "Sale Date", #turn into year
                    "Assessed Value",
                    "Previous Assessed Value",
                    "Taxable Value",
                    "Previous Taxable Value",
                    "Neighborhood",
                    "Permit Status",
                    "violation_date",
                    "fine_amount",
                    "yearly_average",
                    "vacant",
                    "Council District"
                    ]]
clean.head()

,Parcel ID,Taxpayer 1,Taxpayer City,Property Class,Tax Status,Total Floor Area,Total Acreage,Frontage,Depth,Building Count,Year Built,Sale Price,Sale Date,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Permit Status,violation_date,fine_amount,yearly_average,vacant,Council District
239,21062470.,853 ASHLAND LLC,1,401.0,TAXABLE,2468.0,0.079,30.0,115.0,1.0,1916.0,65000.0,9/14/2021 12:00:00 AM,61300.0,46200.0,61300.0,16361.0,Jefferson Chalmers,NaN,2024-04-16,250.0,1602.2,0,4.0
266,21063979.,"CASTLE, ROBERT M",0,401.0,TAXABLE,1389.0,0.000,0.0,0.0,1.0,2002.0,13600.0,2/14/2014 12:00:00 AM,40100.0,31700.0,13286.0,12654.0,Morningside,NaN,NaT,NaN,3541.0,0,4.0
277,21068429.,CITIMORTGAGE INC,0,401.0,TAXABLE,1293.0,0.115,40.0,126.0,1.0,1938.0,79992.0,7/27/2023 12:00:00 AM,40400.0,33400.0,40400.0,15835.0,Moross-Morang,NaN,NaT,NaN,3200.6,0,4.0
278,21069819.,"ROBINSON, DENISE",1,401.0,TAXABLE,1540.0,0.105,40.0,114.0,1.0,1929.0,8912.0,4/30/2010 12:00:00 AM,39900.0,31300.0,14391.0,13706.0,Morningside,NaN,NaT,NaN,3541.0,0,4.0
279,21070146.,"BRADFORD, WILLIAM",1,401.0,TAXABLE,920.0,0.107,40.0,116.0,1.0,1938.0,20000.0,9/1/1987 12:00:00 AM,20300.0,16200.0,9396.0,8949.0,Outer Drive-Hayes,NaN,NaT,NaN,4247.8,0,4.0

In [84]:
#make tax status a binary value
clean['Binary Tax Status'] = np.where(clean['Tax Status'] == "TAXABLE", 1, 0)
clean.drop('Tax Status', axis=1, inplace=True)

<ipython-input-84-78d7a6d5ddc5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean['Binary Tax Status'] = np.where(clean['Tax Status'] == "TAXABLE", 1, 0)
<ipython-input-84-78d7a6d5ddc5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean.drop('Tax Status', axis=1, inplace=True)

In [85]:
clean.head()

,Parcel ID,Taxpayer 1,Taxpayer City,Property Class,Total Floor Area,Total Acreage,Frontage,Depth,Building Count,Year Built,Sale Price,Sale Date,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,Permit Status,violation_date,fine_amount,yearly_average,vacant,Council District,Binary Tax Status
239,21062470.,853 ASHLAND LLC,1,401.0,2468.0,0.079,30.0,115.0,1.0,1916.0,65000.0,9/14/2021 12:00:00 AM,61300.0,46200.0,61300.0,16361.0,Jefferson Chalmers,NaN,2024-04-16,250.0,1602.2,0,4.0,1
266,21063979.,"CASTLE, ROBERT M",0,401.0,1389.0,0.000,0.0,0.0,1.0,2002.0,13600.0,2/14/2014 12:00:00 AM,40100.0,31700.0,13286.0,12654.0,Morningside,NaN,NaT,NaN,3541.0,0,4.0,1
277,21068429.,CITIMORTGAGE INC,0,401.0,1293.0,0.115,40.0,126.0,1.0,1938.0,79992.0,7/27/2023 12:00:00 AM,40400.0,33400.0,40400.0,15835.0,Moross-Morang,NaN,NaT,NaN,3200.6,0,4.0,1
278,21069819.,"ROBINSON, DENISE",1,401.0,1540.0,0.105,40.0,114.0,1.0,1929.0,8912.0,4/30/2010 12:00:00 AM,39900.0,31300.0,14391.0,13706.0,Morningside,NaN,NaT,NaN,3541.0,0,4.0,1
279,21070146.,"BRADFORD, WILLIAM",1,401.0,920.0,0.107,40.0,116.0,1.0,1938.0,20000.0,9/1/1987 12:00:00 AM,20300.0,16200.0,9396.0,8949.0,Outer Drive-Hayes,NaN,NaT,NaN,4247.8,0,4.0,1

In [86]:
#create violation column from violation date
clean["Binary Blight Violation"] = np.where(clean["violation_date"] == "NaT", 0, 1)
clean.drop('violation_date', axis=1, inplace=True)

<ipython-input-86-043fe00a045f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean["Binary Blight Violation"] = np.where(clean["violation_date"] == "NaT", 0, 1)
<ipython-input-86-043fe00a045f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean.drop('violation_date', axis=1, inplace=True)

In [87]:
#create binary building permit status feature from permit status
clean["Binary Building Permit Status"] = np.where(clean["Permit Status"] == "Issued", 1, 0)
clean.drop('Permit Status', axis=1, inplace=True)

<ipython-input-87-39970ac25fcb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean["Binary Building Permit Status"] = np.where(clean["Permit Status"] == "Issued", 1, 0)
<ipython-input-87-39970ac25fcb>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean.drop('Permit Status', axis=1, inplace=True)

In [88]:
#turn sale date into just a year value
clean['Sale Date'] = pd.to_datetime(clean['Sale Date'])

# Extract the year from the 'date' column
clean['Sale Date Year'] = clean['Sale Date'].dt.year
clean['Sale Date Year'] = clean['Sale Date Year']
clean.drop('Sale Date', axis=1, inplace=True)

<ipython-input-88-841f35e8d7b8>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  clean['Sale Date'] = pd.to_datetime(clean['Sale Date'])
<ipython-input-88-841f35e8d7b8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean['Sale Date'] = pd.to_datetime(clean['Sale Date'])
<ipython-input-88-841f35e8d7b8>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean['Sale Date Year'] = clean['Sale Date'].dt.year
<ipython-input-88-841f35e8d7b8>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean['Sale Date Year'] = clean['Sale Date Year']

KeyboardInterrupt:

In [68]:
#taxpayer city is detroit name column cahnge
clean["Taxpayer City is Detroit"] = clean["Taxpayer City"]
clean.drop('Taxpayer City', axis=1, inplace=True)

<ipython-input-68-892a7d72aea8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean["Taxpayer City is Detroit"] = clean["Taxpayer City"]
<ipython-input-68-892a7d72aea8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean.drop('Taxpayer City', axis=1, inplace=True)

In [89]:
#finalized clean data (for now)\
clean.head()

,Parcel ID,Taxpayer 1,Taxpayer City,Property Class,Total Floor Area,Total Acreage,Frontage,Depth,Building Count,Year Built,Sale Price,Sale Date,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,fine_amount,yearly_average,vacant,Council District,Binary Tax Status,Binary Blight Violation,Binary Building Permit Status,Sale Date Year
239,21062470.,853 ASHLAND LLC,1,401.0,2468.0,0.079,30.0,115.0,1.0,1916.0,65000.0,2021-09-14,61300.0,46200.0,61300.0,16361.0,Jefferson Chalmers,250.0,1602.2,0,4.0,1,1,0,2021.0
266,21063979.,"CASTLE, ROBERT M",0,401.0,1389.0,0.000,0.0,0.0,1.0,2002.0,13600.0,2014-02-14,40100.0,31700.0,13286.0,12654.0,Morningside,NaN,3541.0,0,4.0,1,1,0,2014.0
277,21068429.,CITIMORTGAGE INC,0,401.0,1293.0,0.115,40.0,126.0,1.0,1938.0,79992.0,2023-07-27,40400.0,33400.0,40400.0,15835.0,Moross-Morang,NaN,3200.6,0,4.0,1,1,0,2023.0
278,21069819.,"ROBINSON, DENISE",1,401.0,1540.0,0.105,40.0,114.0,1.0,1929.0,8912.0,2010-04-30,39900.0,31300.0,14391.0,13706.0,Morningside,NaN,3541.0,0,4.0,1,1,0,2010.0
279,21070146.,"BRADFORD, WILLIAM",1,401.0,920.0,0.107,40.0,116.0,1.0,1938.0,20000.0,1987-09-01,20300.0,16200.0,9396.0,8949.0,Outer Drive-Hayes,NaN,4247.8,0,4.0,1,1,0,1987.0

In [90]:
len(clean)

211975

In [71]:
#save clean data to drive
#clean.to_csv('/content/drive/MyDrive/detroit data/clean_detroit_data.csv', index=False)
#print('done')

In [72]:
#normalize crime
#new problems-binary blight violations is incorrect or needs revised
#tax status is way too predicitve and needs revised

In [91]:
#replacing NA values in fine_amount to make life easy
df = clean
df['fine_amount'] = df['fine_amount'].fillna(0)
df.head(5)

<ipython-input-91-474026ded9a8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fine_amount'] = df['fine_amount'].fillna(0)

,Parcel ID,Taxpayer 1,Taxpayer City,Property Class,Total Floor Area,Total Acreage,Frontage,Depth,Building Count,Year Built,Sale Price,Sale Date,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,fine_amount,yearly_average,vacant,Council District,Binary Tax Status,Binary Blight Violation,Binary Building Permit Status,Sale Date Year
239,21062470.,853 ASHLAND LLC,1,401.0,2468.0,0.079,30.0,115.0,1.0,1916.0,65000.0,2021-09-14,61300.0,46200.0,61300.0,16361.0,Jefferson Chalmers,250.0,1602.2,0,4.0,1,1,0,2021.0
266,21063979.,"CASTLE, ROBERT M",0,401.0,1389.0,0.000,0.0,0.0,1.0,2002.0,13600.0,2014-02-14,40100.0,31700.0,13286.0,12654.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2014.0
277,21068429.,CITIMORTGAGE INC,0,401.0,1293.0,0.115,40.0,126.0,1.0,1938.0,79992.0,2023-07-27,40400.0,33400.0,40400.0,15835.0,Moross-Morang,0.0,3200.6,0,4.0,1,1,0,2023.0
278,21069819.,"ROBINSON, DENISE",1,401.0,1540.0,0.105,40.0,114.0,1.0,1929.0,8912.0,2010-04-30,39900.0,31300.0,14391.0,13706.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2010.0
279,21070146.,"BRADFORD, WILLIAM",1,401.0,920.0,0.107,40.0,116.0,1.0,1938.0,20000.0,1987-09-01,20300.0,16200.0,9396.0,8949.0,Outer Drive-Hayes,0.0,4247.8,0,4.0,1,1,0,1987.0

In [92]:
#gathering number of houses by neighborhood
housecount = df.groupby('Neighborhood').size().reset_index(name='count')
hcount = housecount.groupby('Neighborhood')['count'].mean().reset_index(name='neighborhood_population')
hcount.head(5)

       Neighborhood  neighborhood_population
0       Airport Sub                   2451.0
1        Arden Park                     63.0
2      Aviation Sub                   1226.0
3            Bagley                   3992.0
4  Barton-McFarland                   3897.0

In [93]:
#gathering number of vacant houses by neighborhood
num_vacant_house = df.groupby('Neighborhood')['vacant'].apply(lambda x: (x==1).sum()).reset_index(name='num_vacant_neighborhood')
num_vacant_house.head()

       Neighborhood  num_vacant_neighborhood
0       Airport Sub                      368
1        Arden Park                        2
2      Aviation Sub                       13
3            Bagley                       83
4  Barton-McFarland                      269

In [94]:
#merging cleaned dataset on neighborhood population info
merged1 = pd.merge(df, hcount, how='left', on='Neighborhood')
merged1.head()

,Parcel ID,Taxpayer 1,Taxpayer City,Property Class,Total Floor Area,Total Acreage,Frontage,Depth,Building Count,Year Built,Sale Price,Sale Date,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,fine_amount,yearly_average,vacant,Council District,Binary Tax Status,Binary Blight Violation,Binary Building Permit Status,Sale Date Year,neighborhood_population
0,21062470.,853 ASHLAND LLC,1,401.0,2468.0,0.079,30.0,115.0,1.0,1916.0,65000.0,2021-09-14,61300.0,46200.0,61300.0,16361.0,Jefferson Chalmers,250.0,1602.2,0,4.0,1,1,0,2021.0,1695.0
1,21063979.,"CASTLE, ROBERT M",0,401.0,1389.0,0.000,0.0,0.0,1.0,2002.0,13600.0,2014-02-14,40100.0,31700.0,13286.0,12654.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2014.0,3606.0
2,21068429.,CITIMORTGAGE INC,0,401.0,1293.0,0.115,40.0,126.0,1.0,1938.0,79992.0,2023-07-27,40400.0,33400.0,40400.0,15835.0,Moross-Morang,0.0,3200.6,0,4.0,1,1,0,2023.0,2610.0
3,21069819.,"ROBINSON, DENISE",1,401.0,1540.0,0.105,40.0,114.0,1.0,1929.0,8912.0,2010-04-30,39900.0,31300.0,14391.0,13706.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2010.0,3606.0
4,21070146.,"BRADFORD, WILLIAM",1,401.0,920.0,0.107,40.0,116.0,1.0,1938.0,20000.0,1987-09-01,20300.0,16200.0,9396.0,8949.0,Outer Drive-Hayes,0.0,4247.8,0,4.0,1,1,0,1987.0,3234.0

In [95]:
#merging number of vacant houses in neighborhood
merged2 =  pd.merge(merged1, num_vacant_house, how='left', on='Neighborhood')
merged2.head()

,Parcel ID,Taxpayer 1,Taxpayer City,Property Class,Total Floor Area,Total Acreage,Frontage,Depth,Building Count,Year Built,Sale Price,Sale Date,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,fine_amount,yearly_average,vacant,Council District,Binary Tax Status,Binary Blight Violation,Binary Building Permit Status,Sale Date Year,neighborhood_population,num_vacant_neighborhood
0,21062470.,853 ASHLAND LLC,1,401.0,2468.0,0.079,30.0,115.0,1.0,1916.0,65000.0,2021-09-14,61300.0,46200.0,61300.0,16361.0,Jefferson Chalmers,250.0,1602.2,0,4.0,1,1,0,2021.0,1695.0,49.0
1,21063979.,"CASTLE, ROBERT M",0,401.0,1389.0,0.000,0.0,0.0,1.0,2002.0,13600.0,2014-02-14,40100.0,31700.0,13286.0,12654.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2014.0,3606.0,152.0
2,21068429.,CITIMORTGAGE INC,0,401.0,1293.0,0.115,40.0,126.0,1.0,1938.0,79992.0,2023-07-27,40400.0,33400.0,40400.0,15835.0,Moross-Morang,0.0,3200.6,0,4.0,1,1,0,2023.0,2610.0,85.0
3,21069819.,"ROBINSON, DENISE",1,401.0,1540.0,0.105,40.0,114.0,1.0,1929.0,8912.0,2010-04-30,39900.0,31300.0,14391.0,13706.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2010.0,3606.0,152.0
4,21070146.,"BRADFORD, WILLIAM",1,401.0,920.0,0.107,40.0,116.0,1.0,1938.0,20000.0,1987-09-01,20300.0,16200.0,9396.0,8949.0,Outer Drive-Hayes,0.0,4247.8,0,4.0,1,1,0,1987.0,3234.0,304.0

In [96]:
#normalizing crime by neighborhood population, removing outliers normalized crime outliers (lost roughly 100 nonvacant homes, 3 vacant homes from this removal)
final = merged2
final['normcrime'] = final['yearly_average']/final['neighborhood_population']
temp = merged2[['Neighborhood','normcrime','yearly_average','neighborhood_population']]
#Lafeyette Park, Rivertown, Brush Park, #Forest Park, Jeffries, Milwaukee Junction, Palmer Park, Rouge Park, West Side Industrial
df_final = final.loc[~try2['Neighborhood'].isin(['Lafayette Park', 'Rivertown','Brush Park', 'Forest Park', 'Jeffries', 'Milwaukee Junction', 'Palmer Park', 'Rouge Park', 'West Side Industrial'])]
df_final.head()

,Parcel ID,Taxpayer 1,Taxpayer City,Property Class,Total Floor Area,Total Acreage,Frontage,Depth,Building Count,Year Built,Sale Price,Sale Date,Assessed Value,Previous Assessed Value,Taxable Value,Previous Taxable Value,Neighborhood,fine_amount,yearly_average,vacant,Council District,Binary Tax Status,Binary Blight Violation,Binary Building Permit Status,Sale Date Year,neighborhood_population,num_vacant_neighborhood,normcrime
0,21062470.,853 ASHLAND LLC,1,401.0,2468.0,0.079,30.0,115.0,1.0,1916.0,65000.0,2021-09-14,61300.0,46200.0,61300.0,16361.0,Jefferson Chalmers,250.0,1602.2,0,4.0,1,1,0,2021.0,1695.0,49.0,0.945251
1,21063979.,"CASTLE, ROBERT M",0,401.0,1389.0,0.000,0.0,0.0,1.0,2002.0,13600.0,2014-02-14,40100.0,31700.0,13286.0,12654.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2014.0,3606.0,152.0,0.981974
2,21068429.,CITIMORTGAGE INC,0,401.0,1293.0,0.115,40.0,126.0,1.0,1938.0,79992.0,2023-07-27,40400.0,33400.0,40400.0,15835.0,Moross-Morang,0.0,3200.6,0,4.0,1,1,0,2023.0,2610.0,85.0,1.226284
3,21069819.,"ROBINSON, DENISE",1,401.0,1540.0,0.105,40.0,114.0,1.0,1929.0,8912.0,2010-04-30,39900.0,31300.0,14391.0,13706.0,Morningside,0.0,3541.0,0,4.0,1,1,0,2010.0,3606.0,152.0,0.981974
4,21070146.,"BRADFORD, WILLIAM",1,401.0,920.0,0.107,40.0,116.0,1.0,1938.0,20000.0,1987-09-01,20300.0,16200.0,9396.0,8949.0,Outer Drive-Hayes,0.0,4247.8,0,4.0,1,1,0,1987.0,3234.0,304.0,1.313482

In [99]:
vacant_rows = df_final[df_final["vacant"] == 1]

#percentage of vacant rows where previous assessed value is 0
percent_with_prev_value_zero = (vacant_rows["Previous Assessed Value"] == 0).mean() * 100

print(f"Percentage of vacant rows with Previous Assessed Value of 0: {percent_with_prev_value_zero:.2f}%")

Percentage of vacant rows with Previous Assessed Value of 0: 66.63%

In [100]:
#checking all columns are present
bolsdkfds = df_final.keys().tolist()
bolsdkfds

['Parcel ID',
 'Taxpayer 1',
 'Taxpayer City',
 'Property Class',
 'Total Floor Area',
 'Total Acreage',
 'Frontage',
 'Depth',
 'Building Count',
 'Year Built',
 'Sale Price',
 'Sale Date',
 'Assessed Value',
 'Previous Assessed Value',
 'Taxable Value',
 'Previous Taxable Value',
 'Neighborhood',
 'fine_amount',
 'yearly_average',
 'vacant',
 'Council District',
 'Binary Tax Status',
 'Binary Blight Violation',
 'Binary Building Permit Status',
 'Sale Date Year',
 'neighborhood_population',
 'num_vacant_neighborhood',
 'normcrime']

In [81]:
##export final dataset to drive folder
#df_final.to_csv('/content/drive/MyDrive/detroit data/final_cleaned_detroit.csv', index=False)

In [101]:
#save clean data to drive
df_final.to_csv('/content/drive/MyDrive/detroit data/final_cleaned_detroit.csv', index=False)
print('done')

done